package com.dream.auth.dao;

import com.dream.auth.model.AuthLog;
import com.dream.auth.model.AuthLogCriteria;
import com.dream.rapid.base.BaseIbatisDao;

public class AuthLogDAO extends BaseIbatisDao<AuthLog,java.lang.String,AuthLogCriteria> {
	
	//================================********Generated code start here********================================

	public final static String TOP_AUTH_LOG = "TOP_AUTH_LOG"; 
	
	@Override
	protected String getIbatisSqlMapNamespace() {
		return TOP_AUTH_LOG;
	}
	



    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table TOP_AUTH_LOG
     *
     *  Mon Sep 29 16:12:22 CST 2014
     */
    private static class UpdateByCriteriaParms extends AuthLogCriteria {
        private Object record;

        public UpdateByCriteriaParms(Object record, AuthLogCriteria criteria) {
            super(criteria);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }


	@Override
	protected void prepareObjectForSaveOrUpdate(AuthLog source,AuthLog dest) {
	}


	@Override
	protected AuthLogCriteria getCriteriaParam(AuthLog record,
			AuthLogCriteria criteria) {
		return new UpdateByCriteriaParms(record,criteria);
	}
	
	//================================********Generated code end here********================================
	
	//================================********Customized code start here********==============================

	
	
	
	//================================********Customized code start here********==============================
}