package com.dream.menu.model;

import java.io.Serializable;

public class Menu implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_MENU.MENU_ID
     *
     *  Mon Sep 29 17:55:43 CST 2014
     */
    private String menuId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_MENU.MENU_NAME_CN
     *
     *  Mon Sep 29 17:55:43 CST 2014
     */
    private String menuNameCn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_MENU.LFT_VALUE
     *
     *  Mon Sep 29 17:55:43 CST 2014
     */
    private String lftValue;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_MENU.RGT_VALUE
     *
     *  Mon Sep 29 17:55:43 CST 2014
     */
    private String rgtValue;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_MENU.ORDER_NUM
     *
     *  Mon Sep 29 17:55:43 CST 2014
     */
    private Integer orderNum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_MENU.MENU_NAME_EN
     *
     *  Mon Sep 29 17:55:43 CST 2014
     */
    private String menuNameEn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table TOP_MENU
     *
     *  Mon Sep 29 17:55:43 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_MENU.MENU_ID
     *
     * @return the value of TOP_MENU.MENU_ID
     *
     *  Mon Sep 29 17:55:43 CST 2014
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_MENU.MENU_ID
     *
     * @param menuId the value for TOP_MENU.MENU_ID
     *
     *  Mon Sep 29 17:55:43 CST 2014
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_MENU.MENU_NAME_CN
     *
     * @return the value of TOP_MENU.MENU_NAME_CN
     *
     *  Mon Sep 29 17:55:43 CST 2014
     */
    public String getMenuNameCn() {
        return menuNameCn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_MENU.MENU_NAME_CN
     *
     * @param menuNameCn the value for TOP_MENU.MENU_NAME_CN
     *
     *  Mon Sep 29 17:55:43 CST 2014
     */
    public void setMenuNameCn(String menuNameCn) {
        this.menuNameCn = menuNameCn == null ? null : menuNameCn.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_MENU.LFT_VALUE
     *
     * @return the value of TOP_MENU.LFT_VALUE
     *
     *  Mon Sep 29 17:55:43 CST 2014
     */
    public String getLftValue() {
        return lftValue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_MENU.LFT_VALUE
     *
     * @param lftValue the value for TOP_MENU.LFT_VALUE
     *
     *  Mon Sep 29 17:55:43 CST 2014
     */
    public void setLftValue(String lftValue) {
        this.lftValue = lftValue == null ? null : lftValue.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_MENU.RGT_VALUE
     *
     * @return the value of TOP_MENU.RGT_VALUE
     *
     *  Mon Sep 29 17:55:43 CST 2014
     */
    public String getRgtValue() {
        return rgtValue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_MENU.RGT_VALUE
     *
     * @param rgtValue the value for TOP_MENU.RGT_VALUE
     *
     *  Mon Sep 29 17:55:43 CST 2014
     */
    public void setRgtValue(String rgtValue) {
        this.rgtValue = rgtValue == null ? null : rgtValue.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_MENU.ORDER_NUM
     *
     * @return the value of TOP_MENU.ORDER_NUM
     *
     *  Mon Sep 29 17:55:43 CST 2014
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_MENU.ORDER_NUM
     *
     * @param orderNum the value for TOP_MENU.ORDER_NUM
     *
     *  Mon Sep 29 17:55:43 CST 2014
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_MENU.MENU_NAME_EN
     *
     * @return the value of TOP_MENU.MENU_NAME_EN
     *
     *  Mon Sep 29 17:55:43 CST 2014
     */
    public String getMenuNameEn() {
        return menuNameEn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_MENU.MENU_NAME_EN
     *
     * @param menuNameEn the value for TOP_MENU.MENU_NAME_EN
     *
     *  Mon Sep 29 17:55:43 CST 2014
     */
    public void setMenuNameEn(String menuNameEn) {
        this.menuNameEn = menuNameEn == null ? null : menuNameEn.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_MENU
     *
     *  Mon Sep 29 17:55:43 CST 2014
     */
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof Menu)) {
            return false;
        }
        Menu other = (Menu) that;
        return this.getMenuId() == null ? other == null : this.getMenuId().equals(other.getMenuId())
            && this.getMenuNameCn() == null ? other == null : this.getMenuNameCn().equals(other.getMenuNameCn())
            && this.getLftValue() == null ? other == null : this.getLftValue().equals(other.getLftValue())
            && this.getRgtValue() == null ? other == null : this.getRgtValue().equals(other.getRgtValue())
            && this.getOrderNum() == null ? other == null : this.getOrderNum().equals(other.getOrderNum())
            && this.getMenuNameEn() == null ? other == null : this.getMenuNameEn().equals(other.getMenuNameEn());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_MENU
     *
     *  Mon Sep 29 17:55:43 CST 2014
     */
    public int hashCode() {
        int hash = 23;
        if (getMenuId() != null) {
            hash *= getMenuId().hashCode();
        }
        if (getMenuNameCn() != null) {
            hash *= getMenuNameCn().hashCode();
        }
        if (getLftValue() != null) {
            hash *= getLftValue().hashCode();
        }
        if (getRgtValue() != null) {
            hash *= getRgtValue().hashCode();
        }
        if (getOrderNum() != null) {
            hash *= getOrderNum().hashCode();
        }
        if (getMenuNameEn() != null) {
            hash *= getMenuNameEn().hashCode();
        }
        return hash;
    }
}