package com.dream.auth.model;

import java.io.Serializable;
import java.util.Date;

public class AuthLog implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_AUTH_LOG.LOG_ID
     *
     *  Mon Sep 29 15:27:39 CST 2014
     */
    private String logId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_AUTH_LOG.SESSION_ID
     *
     *  Mon Sep 29 15:27:39 CST 2014
     */
    private String sessionId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_AUTH_LOG.CLIENT_IP
     *
     *  Mon Sep 29 15:27:39 CST 2014
     */
    private String clientIp;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_AUTH_LOG.CLIENT_OS
     *
     *  Mon Sep 29 15:27:39 CST 2014
     */
    private String clientOs;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_AUTH_LOG.CLIENT_BROWSER
     *
     *  Mon Sep 29 15:27:39 CST 2014
     */
    private String clientBrowser;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_AUTH_LOG.USER_ID
     *
     *  Mon Sep 29 15:27:39 CST 2014
     */
    private Long userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_AUTH_LOG.AUTH_TIME
     *
     *  Mon Sep 29 15:27:39 CST 2014
     */
    private Date authTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table TOP_AUTH_LOG
     *
     *  Mon Sep 29 15:27:39 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_AUTH_LOG.LOG_ID
     *
     * @return the value of TOP_AUTH_LOG.LOG_ID
     *
     *  Mon Sep 29 15:27:39 CST 2014
     */
    public String getLogId() {
        return logId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_AUTH_LOG.LOG_ID
     *
     * @param logId the value for TOP_AUTH_LOG.LOG_ID
     *
     *  Mon Sep 29 15:27:39 CST 2014
     */
    public void setLogId(String logId) {
        this.logId = logId == null ? null : logId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_AUTH_LOG.SESSION_ID
     *
     * @return the value of TOP_AUTH_LOG.SESSION_ID
     *
     *  Mon Sep 29 15:27:39 CST 2014
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_AUTH_LOG.SESSION_ID
     *
     * @param sessionId the value for TOP_AUTH_LOG.SESSION_ID
     *
     *  Mon Sep 29 15:27:39 CST 2014
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId == null ? null : sessionId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_AUTH_LOG.CLIENT_IP
     *
     * @return the value of TOP_AUTH_LOG.CLIENT_IP
     *
     *  Mon Sep 29 15:27:39 CST 2014
     */
    public String getClientIp() {
        return clientIp;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_AUTH_LOG.CLIENT_IP
     *
     * @param clientIp the value for TOP_AUTH_LOG.CLIENT_IP
     *
     *  Mon Sep 29 15:27:39 CST 2014
     */
    public void setClientIp(String clientIp) {
        this.clientIp = clientIp == null ? null : clientIp.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_AUTH_LOG.CLIENT_OS
     *
     * @return the value of TOP_AUTH_LOG.CLIENT_OS
     *
     *  Mon Sep 29 15:27:39 CST 2014
     */
    public String getClientOs() {
        return clientOs;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_AUTH_LOG.CLIENT_OS
     *
     * @param clientOs the value for TOP_AUTH_LOG.CLIENT_OS
     *
     *  Mon Sep 29 15:27:39 CST 2014
     */
    public void setClientOs(String clientOs) {
        this.clientOs = clientOs == null ? null : clientOs.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_AUTH_LOG.CLIENT_BROWSER
     *
     * @return the value of TOP_AUTH_LOG.CLIENT_BROWSER
     *
     *  Mon Sep 29 15:27:39 CST 2014
     */
    public String getClientBrowser() {
        return clientBrowser;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_AUTH_LOG.CLIENT_BROWSER
     *
     * @param clientBrowser the value for TOP_AUTH_LOG.CLIENT_BROWSER
     *
     *  Mon Sep 29 15:27:39 CST 2014
     */
    public void setClientBrowser(String clientBrowser) {
        this.clientBrowser = clientBrowser == null ? null : clientBrowser.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_AUTH_LOG.USER_ID
     *
     * @return the value of TOP_AUTH_LOG.USER_ID
     *
     *  Mon Sep 29 15:27:39 CST 2014
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_AUTH_LOG.USER_ID
     *
     * @param userId the value for TOP_AUTH_LOG.USER_ID
     *
     *  Mon Sep 29 15:27:39 CST 2014
     */
    public void setUserId(Long userId) {
        this.userId = userId == null ? null : userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_AUTH_LOG.AUTH_TIME
     *
     * @return the value of TOP_AUTH_LOG.AUTH_TIME
     *
     *  Mon Sep 29 15:27:39 CST 2014
     */
    public Date getAuthTime() {
        return authTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_AUTH_LOG.AUTH_TIME
     *
     * @param authTime the value for TOP_AUTH_LOG.AUTH_TIME
     *
     *  Mon Sep 29 15:27:39 CST 2014
     */
    public void setAuthTime(Date authTime) {
        this.authTime = authTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_AUTH_LOG
     *
     *  Mon Sep 29 15:27:39 CST 2014
     */
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof AuthLog)) {
            return false;
        }
        AuthLog other = (AuthLog) that;
        return this.getLogId() == null ? other == null : this.getLogId().equals(other.getLogId())
            && this.getSessionId() == null ? other == null : this.getSessionId().equals(other.getSessionId())
            && this.getClientIp() == null ? other == null : this.getClientIp().equals(other.getClientIp())
            && this.getClientOs() == null ? other == null : this.getClientOs().equals(other.getClientOs())
            && this.getClientBrowser() == null ? other == null : this.getClientBrowser().equals(other.getClientBrowser())
            && this.getUserId() == null ? other == null : this.getUserId().equals(other.getUserId())
            && this.getAuthTime() == null ? other == null : this.getAuthTime().equals(other.getAuthTime());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_AUTH_LOG
     *
     *  Mon Sep 29 15:27:39 CST 2014
     */
    public int hashCode() {
        int hash = 23;
        if (getLogId() != null) {
            hash *= getLogId().hashCode();
        }
        if (getSessionId() != null) {
            hash *= getSessionId().hashCode();
        }
        if (getClientIp() != null) {
            hash *= getClientIp().hashCode();
        }
        if (getClientOs() != null) {
            hash *= getClientOs().hashCode();
        }
        if (getClientBrowser() != null) {
            hash *= getClientBrowser().hashCode();
        }
        if (getUserId() != null) {
            hash *= getUserId().hashCode();
        }
        if (getAuthTime() != null) {
            hash *= getAuthTime().hashCode();
        }
        return hash;
    }
}