package com.dream.auth.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AuthCriteria {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table TOP_AUTH
     *
     *  Sat Oct 04 22:12:31 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table TOP_AUTH
     *
     *  Sat Oct 04 22:12:31 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_AUTH
     *
     *  Sat Oct 04 22:12:31 CST 2014
     */
    public AuthCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_AUTH
     *
     *  Sat Oct 04 22:12:31 CST 2014
     */
    protected AuthCriteria(AuthCriteria example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_AUTH
     *
     *  Sat Oct 04 22:12:31 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_AUTH
     *
     *  Sat Oct 04 22:12:31 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_AUTH
     *
     *  Sat Oct 04 22:12:31 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_AUTH
     *
     *  Sat Oct 04 22:12:31 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_AUTH
     *
     *  Sat Oct 04 22:12:31 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_AUTH
     *
     *  Sat Oct 04 22:12:31 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_AUTH
     *
     *  Sat Oct 04 22:12:31 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table TOP_AUTH
     *
     *  Sat Oct 04 22:12:31 CST 2014
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("USER_ID =", value, "userId");
            return this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("USER_ID <>", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("USER_ID >", value, "userId");
            return this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("USER_ID >=", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("USER_ID <", value, "userId");
            return this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("USER_ID <=", value, "userId");
            return this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("USER_ID in", values, "userId");
            return this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("USER_ID not in", values, "userId");
            return this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return this;
        }

        public Criteria andIsLockIsNull() {
            addCriterion("IS_LOCK is null");
            return this;
        }

        public Criteria andIsLockIsNotNull() {
            addCriterion("IS_LOCK is not null");
            return this;
        }

        public Criteria andIsLockEqualTo(String value) {
            addCriterion("IS_LOCK =", value, "isLock");
            return this;
        }

        public Criteria andIsLockNotEqualTo(String value) {
            addCriterion("IS_LOCK <>", value, "isLock");
            return this;
        }

        public Criteria andIsLockGreaterThan(String value) {
            addCriterion("IS_LOCK >", value, "isLock");
            return this;
        }

        public Criteria andIsLockGreaterThanOrEqualTo(String value) {
            addCriterion("IS_LOCK >=", value, "isLock");
            return this;
        }

        public Criteria andIsLockLessThan(String value) {
            addCriterion("IS_LOCK <", value, "isLock");
            return this;
        }

        public Criteria andIsLockLessThanOrEqualTo(String value) {
            addCriterion("IS_LOCK <=", value, "isLock");
            return this;
        }

        public Criteria andIsLockLike(String value) {
            addCriterion("IS_LOCK like", value, "isLock");
            return this;
        }

        public Criteria andIsLockNotLike(String value) {
            addCriterion("IS_LOCK not like", value, "isLock");
            return this;
        }

        public Criteria andIsLockIn(List<String> values) {
            addCriterion("IS_LOCK in", values, "isLock");
            return this;
        }

        public Criteria andIsLockNotIn(List<String> values) {
            addCriterion("IS_LOCK not in", values, "isLock");
            return this;
        }

        public Criteria andIsLockBetween(String value1, String value2) {
            addCriterion("IS_LOCK between", value1, value2, "isLock");
            return this;
        }

        public Criteria andIsLockNotBetween(String value1, String value2) {
            addCriterion("IS_LOCK not between", value1, value2, "isLock");
            return this;
        }

        public Criteria andIsEnableIsNull() {
            addCriterion("IS_ENABLE is null");
            return this;
        }

        public Criteria andIsEnableIsNotNull() {
            addCriterion("IS_ENABLE is not null");
            return this;
        }

        public Criteria andIsEnableEqualTo(String value) {
            addCriterion("IS_ENABLE =", value, "isEnable");
            return this;
        }

        public Criteria andIsEnableNotEqualTo(String value) {
            addCriterion("IS_ENABLE <>", value, "isEnable");
            return this;
        }

        public Criteria andIsEnableGreaterThan(String value) {
            addCriterion("IS_ENABLE >", value, "isEnable");
            return this;
        }

        public Criteria andIsEnableGreaterThanOrEqualTo(String value) {
            addCriterion("IS_ENABLE >=", value, "isEnable");
            return this;
        }

        public Criteria andIsEnableLessThan(String value) {
            addCriterion("IS_ENABLE <", value, "isEnable");
            return this;
        }

        public Criteria andIsEnableLessThanOrEqualTo(String value) {
            addCriterion("IS_ENABLE <=", value, "isEnable");
            return this;
        }

        public Criteria andIsEnableLike(String value) {
            addCriterion("IS_ENABLE like", value, "isEnable");
            return this;
        }

        public Criteria andIsEnableNotLike(String value) {
            addCriterion("IS_ENABLE not like", value, "isEnable");
            return this;
        }

        public Criteria andIsEnableIn(List<String> values) {
            addCriterion("IS_ENABLE in", values, "isEnable");
            return this;
        }

        public Criteria andIsEnableNotIn(List<String> values) {
            addCriterion("IS_ENABLE not in", values, "isEnable");
            return this;
        }

        public Criteria andIsEnableBetween(String value1, String value2) {
            addCriterion("IS_ENABLE between", value1, value2, "isEnable");
            return this;
        }

        public Criteria andIsEnableNotBetween(String value1, String value2) {
            addCriterion("IS_ENABLE not between", value1, value2, "isEnable");
            return this;
        }

        public Criteria andTaobaoUserNickIsNull() {
            addCriterion("TAOBAO_USER_NICK is null");
            return this;
        }

        public Criteria andTaobaoUserNickIsNotNull() {
            addCriterion("TAOBAO_USER_NICK is not null");
            return this;
        }

        public Criteria andTaobaoUserNickEqualTo(String value) {
            addCriterion("TAOBAO_USER_NICK =", value, "taobaoUserNick");
            return this;
        }

        public Criteria andTaobaoUserNickNotEqualTo(String value) {
            addCriterion("TAOBAO_USER_NICK <>", value, "taobaoUserNick");
            return this;
        }

        public Criteria andTaobaoUserNickGreaterThan(String value) {
            addCriterion("TAOBAO_USER_NICK >", value, "taobaoUserNick");
            return this;
        }

        public Criteria andTaobaoUserNickGreaterThanOrEqualTo(String value) {
            addCriterion("TAOBAO_USER_NICK >=", value, "taobaoUserNick");
            return this;
        }

        public Criteria andTaobaoUserNickLessThan(String value) {
            addCriterion("TAOBAO_USER_NICK <", value, "taobaoUserNick");
            return this;
        }

        public Criteria andTaobaoUserNickLessThanOrEqualTo(String value) {
            addCriterion("TAOBAO_USER_NICK <=", value, "taobaoUserNick");
            return this;
        }

        public Criteria andTaobaoUserNickLike(String value) {
            addCriterion("TAOBAO_USER_NICK like", value, "taobaoUserNick");
            return this;
        }

        public Criteria andTaobaoUserNickNotLike(String value) {
            addCriterion("TAOBAO_USER_NICK not like", value, "taobaoUserNick");
            return this;
        }

        public Criteria andTaobaoUserNickIn(List<String> values) {
            addCriterion("TAOBAO_USER_NICK in", values, "taobaoUserNick");
            return this;
        }

        public Criteria andTaobaoUserNickNotIn(List<String> values) {
            addCriterion("TAOBAO_USER_NICK not in", values, "taobaoUserNick");
            return this;
        }

        public Criteria andTaobaoUserNickBetween(String value1, String value2) {
            addCriterion("TAOBAO_USER_NICK between", value1, value2, "taobaoUserNick");
            return this;
        }

        public Criteria andTaobaoUserNickNotBetween(String value1, String value2) {
            addCriterion("TAOBAO_USER_NICK not between", value1, value2, "taobaoUserNick");
            return this;
        }

        public Criteria andTaobaoUserIdIsNull() {
            addCriterion("TAOBAO_USER_ID is null");
            return this;
        }

        public Criteria andTaobaoUserIdIsNotNull() {
            addCriterion("TAOBAO_USER_ID is not null");
            return this;
        }

        public Criteria andTaobaoUserIdEqualTo(String value) {
            addCriterion("TAOBAO_USER_ID =", value, "taobaoUserId");
            return this;
        }

        public Criteria andTaobaoUserIdNotEqualTo(String value) {
            addCriterion("TAOBAO_USER_ID <>", value, "taobaoUserId");
            return this;
        }

        public Criteria andTaobaoUserIdGreaterThan(String value) {
            addCriterion("TAOBAO_USER_ID >", value, "taobaoUserId");
            return this;
        }

        public Criteria andTaobaoUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("TAOBAO_USER_ID >=", value, "taobaoUserId");
            return this;
        }

        public Criteria andTaobaoUserIdLessThan(String value) {
            addCriterion("TAOBAO_USER_ID <", value, "taobaoUserId");
            return this;
        }

        public Criteria andTaobaoUserIdLessThanOrEqualTo(String value) {
            addCriterion("TAOBAO_USER_ID <=", value, "taobaoUserId");
            return this;
        }

        public Criteria andTaobaoUserIdLike(String value) {
            addCriterion("TAOBAO_USER_ID like", value, "taobaoUserId");
            return this;
        }

        public Criteria andTaobaoUserIdNotLike(String value) {
            addCriterion("TAOBAO_USER_ID not like", value, "taobaoUserId");
            return this;
        }

        public Criteria andTaobaoUserIdIn(List<String> values) {
            addCriterion("TAOBAO_USER_ID in", values, "taobaoUserId");
            return this;
        }

        public Criteria andTaobaoUserIdNotIn(List<String> values) {
            addCriterion("TAOBAO_USER_ID not in", values, "taobaoUserId");
            return this;
        }

        public Criteria andTaobaoUserIdBetween(String value1, String value2) {
            addCriterion("TAOBAO_USER_ID between", value1, value2, "taobaoUserId");
            return this;
        }

        public Criteria andTaobaoUserIdNotBetween(String value1, String value2) {
            addCriterion("TAOBAO_USER_ID not between", value1, value2, "taobaoUserId");
            return this;
        }

        public Criteria andSubTaobaoUserIdIsNull() {
            addCriterion("SUB_TAOBAO_USER_ID is null");
            return this;
        }

        public Criteria andSubTaobaoUserIdIsNotNull() {
            addCriterion("SUB_TAOBAO_USER_ID is not null");
            return this;
        }

        public Criteria andSubTaobaoUserIdEqualTo(String value) {
            addCriterion("SUB_TAOBAO_USER_ID =", value, "subTaobaoUserId");
            return this;
        }

        public Criteria andSubTaobaoUserIdNotEqualTo(String value) {
            addCriterion("SUB_TAOBAO_USER_ID <>", value, "subTaobaoUserId");
            return this;
        }

        public Criteria andSubTaobaoUserIdGreaterThan(String value) {
            addCriterion("SUB_TAOBAO_USER_ID >", value, "subTaobaoUserId");
            return this;
        }

        public Criteria andSubTaobaoUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("SUB_TAOBAO_USER_ID >=", value, "subTaobaoUserId");
            return this;
        }

        public Criteria andSubTaobaoUserIdLessThan(String value) {
            addCriterion("SUB_TAOBAO_USER_ID <", value, "subTaobaoUserId");
            return this;
        }

        public Criteria andSubTaobaoUserIdLessThanOrEqualTo(String value) {
            addCriterion("SUB_TAOBAO_USER_ID <=", value, "subTaobaoUserId");
            return this;
        }

        public Criteria andSubTaobaoUserIdLike(String value) {
            addCriterion("SUB_TAOBAO_USER_ID like", value, "subTaobaoUserId");
            return this;
        }

        public Criteria andSubTaobaoUserIdNotLike(String value) {
            addCriterion("SUB_TAOBAO_USER_ID not like", value, "subTaobaoUserId");
            return this;
        }

        public Criteria andSubTaobaoUserIdIn(List<String> values) {
            addCriterion("SUB_TAOBAO_USER_ID in", values, "subTaobaoUserId");
            return this;
        }

        public Criteria andSubTaobaoUserIdNotIn(List<String> values) {
            addCriterion("SUB_TAOBAO_USER_ID not in", values, "subTaobaoUserId");
            return this;
        }

        public Criteria andSubTaobaoUserIdBetween(String value1, String value2) {
            addCriterion("SUB_TAOBAO_USER_ID between", value1, value2, "subTaobaoUserId");
            return this;
        }

        public Criteria andSubTaobaoUserIdNotBetween(String value1, String value2) {
            addCriterion("SUB_TAOBAO_USER_ID not between", value1, value2, "subTaobaoUserId");
            return this;
        }

        public Criteria andSubTaobaoUserNickIsNull() {
            addCriterion("SUB_TAOBAO_USER_NICK is null");
            return this;
        }

        public Criteria andSubTaobaoUserNickIsNotNull() {
            addCriterion("SUB_TAOBAO_USER_NICK is not null");
            return this;
        }

        public Criteria andSubTaobaoUserNickEqualTo(String value) {
            addCriterion("SUB_TAOBAO_USER_NICK =", value, "subTaobaoUserNick");
            return this;
        }

        public Criteria andSubTaobaoUserNickNotEqualTo(String value) {
            addCriterion("SUB_TAOBAO_USER_NICK <>", value, "subTaobaoUserNick");
            return this;
        }

        public Criteria andSubTaobaoUserNickGreaterThan(String value) {
            addCriterion("SUB_TAOBAO_USER_NICK >", value, "subTaobaoUserNick");
            return this;
        }

        public Criteria andSubTaobaoUserNickGreaterThanOrEqualTo(String value) {
            addCriterion("SUB_TAOBAO_USER_NICK >=", value, "subTaobaoUserNick");
            return this;
        }

        public Criteria andSubTaobaoUserNickLessThan(String value) {
            addCriterion("SUB_TAOBAO_USER_NICK <", value, "subTaobaoUserNick");
            return this;
        }

        public Criteria andSubTaobaoUserNickLessThanOrEqualTo(String value) {
            addCriterion("SUB_TAOBAO_USER_NICK <=", value, "subTaobaoUserNick");
            return this;
        }

        public Criteria andSubTaobaoUserNickLike(String value) {
            addCriterion("SUB_TAOBAO_USER_NICK like", value, "subTaobaoUserNick");
            return this;
        }

        public Criteria andSubTaobaoUserNickNotLike(String value) {
            addCriterion("SUB_TAOBAO_USER_NICK not like", value, "subTaobaoUserNick");
            return this;
        }

        public Criteria andSubTaobaoUserNickIn(List<String> values) {
            addCriterion("SUB_TAOBAO_USER_NICK in", values, "subTaobaoUserNick");
            return this;
        }

        public Criteria andSubTaobaoUserNickNotIn(List<String> values) {
            addCriterion("SUB_TAOBAO_USER_NICK not in", values, "subTaobaoUserNick");
            return this;
        }

        public Criteria andSubTaobaoUserNickBetween(String value1, String value2) {
            addCriterion("SUB_TAOBAO_USER_NICK between", value1, value2, "subTaobaoUserNick");
            return this;
        }

        public Criteria andSubTaobaoUserNickNotBetween(String value1, String value2) {
            addCriterion("SUB_TAOBAO_USER_NICK not between", value1, value2, "subTaobaoUserNick");
            return this;
        }

        public Criteria andRefreshedTimeIsNull() {
            addCriterion("REFRESHED_TIME is null");
            return this;
        }

        public Criteria andRefreshedTimeIsNotNull() {
            addCriterion("REFRESHED_TIME is not null");
            return this;
        }

        public Criteria andRefreshedTimeEqualTo(Date value) {
            addCriterion("REFRESHED_TIME =", value, "refreshedTime");
            return this;
        }

        public Criteria andRefreshedTimeNotEqualTo(Date value) {
            addCriterion("REFRESHED_TIME <>", value, "refreshedTime");
            return this;
        }

        public Criteria andRefreshedTimeGreaterThan(Date value) {
            addCriterion("REFRESHED_TIME >", value, "refreshedTime");
            return this;
        }

        public Criteria andRefreshedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("REFRESHED_TIME >=", value, "refreshedTime");
            return this;
        }

        public Criteria andRefreshedTimeLessThan(Date value) {
            addCriterion("REFRESHED_TIME <", value, "refreshedTime");
            return this;
        }

        public Criteria andRefreshedTimeLessThanOrEqualTo(Date value) {
            addCriterion("REFRESHED_TIME <=", value, "refreshedTime");
            return this;
        }

        public Criteria andRefreshedTimeIn(List<Date> values) {
            addCriterion("REFRESHED_TIME in", values, "refreshedTime");
            return this;
        }

        public Criteria andRefreshedTimeNotIn(List<Date> values) {
            addCriterion("REFRESHED_TIME not in", values, "refreshedTime");
            return this;
        }

        public Criteria andRefreshedTimeBetween(Date value1, Date value2) {
            addCriterion("REFRESHED_TIME between", value1, value2, "refreshedTime");
            return this;
        }

        public Criteria andRefreshedTimeNotBetween(Date value1, Date value2) {
            addCriterion("REFRESHED_TIME not between", value1, value2, "refreshedTime");
            return this;
        }

        public Criteria andShopIdIsNull() {
            addCriterion("SHOP_ID is null");
            return this;
        }

        public Criteria andShopIdIsNotNull() {
            addCriterion("SHOP_ID is not null");
            return this;
        }

        public Criteria andShopIdEqualTo(Long value) {
            addCriterion("SHOP_ID =", value, "shopId");
            return this;
        }

        public Criteria andShopIdNotEqualTo(Long value) {
            addCriterion("SHOP_ID <>", value, "shopId");
            return this;
        }

        public Criteria andShopIdGreaterThan(Long value) {
            addCriterion("SHOP_ID >", value, "shopId");
            return this;
        }

        public Criteria andShopIdGreaterThanOrEqualTo(Long value) {
            addCriterion("SHOP_ID >=", value, "shopId");
            return this;
        }

        public Criteria andShopIdLessThan(Long value) {
            addCriterion("SHOP_ID <", value, "shopId");
            return this;
        }

        public Criteria andShopIdLessThanOrEqualTo(Long value) {
            addCriterion("SHOP_ID <=", value, "shopId");
            return this;
        }

        public Criteria andShopIdIn(List<Long> values) {
            addCriterion("SHOP_ID in", values, "shopId");
            return this;
        }

        public Criteria andShopIdNotIn(List<Long> values) {
            addCriterion("SHOP_ID not in", values, "shopId");
            return this;
        }

        public Criteria andShopIdBetween(Long value1, Long value2) {
            addCriterion("SHOP_ID between", value1, value2, "shopId");
            return this;
        }

        public Criteria andShopIdNotBetween(Long value1, Long value2) {
            addCriterion("SHOP_ID not between", value1, value2, "shopId");
            return this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return this;
        }

        public Criteria andAccessTokenIsNull() {
            addCriterion("ACCESS_TOKEN is null");
            return this;
        }

        public Criteria andAccessTokenIsNotNull() {
            addCriterion("ACCESS_TOKEN is not null");
            return this;
        }

        public Criteria andAccessTokenEqualTo(String value) {
            addCriterion("ACCESS_TOKEN =", value, "accessToken");
            return this;
        }

        public Criteria andAccessTokenNotEqualTo(String value) {
            addCriterion("ACCESS_TOKEN <>", value, "accessToken");
            return this;
        }

        public Criteria andAccessTokenGreaterThan(String value) {
            addCriterion("ACCESS_TOKEN >", value, "accessToken");
            return this;
        }

        public Criteria andAccessTokenGreaterThanOrEqualTo(String value) {
            addCriterion("ACCESS_TOKEN >=", value, "accessToken");
            return this;
        }

        public Criteria andAccessTokenLessThan(String value) {
            addCriterion("ACCESS_TOKEN <", value, "accessToken");
            return this;
        }

        public Criteria andAccessTokenLessThanOrEqualTo(String value) {
            addCriterion("ACCESS_TOKEN <=", value, "accessToken");
            return this;
        }

        public Criteria andAccessTokenLike(String value) {
            addCriterion("ACCESS_TOKEN like", value, "accessToken");
            return this;
        }

        public Criteria andAccessTokenNotLike(String value) {
            addCriterion("ACCESS_TOKEN not like", value, "accessToken");
            return this;
        }

        public Criteria andAccessTokenIn(List<String> values) {
            addCriterion("ACCESS_TOKEN in", values, "accessToken");
            return this;
        }

        public Criteria andAccessTokenNotIn(List<String> values) {
            addCriterion("ACCESS_TOKEN not in", values, "accessToken");
            return this;
        }

        public Criteria andAccessTokenBetween(String value1, String value2) {
            addCriterion("ACCESS_TOKEN between", value1, value2, "accessToken");
            return this;
        }

        public Criteria andAccessTokenNotBetween(String value1, String value2) {
            addCriterion("ACCESS_TOKEN not between", value1, value2, "accessToken");
            return this;
        }

        public Criteria andTokenTypeIsNull() {
            addCriterion("TOKEN_TYPE is null");
            return this;
        }

        public Criteria andTokenTypeIsNotNull() {
            addCriterion("TOKEN_TYPE is not null");
            return this;
        }

        public Criteria andTokenTypeEqualTo(String value) {
            addCriterion("TOKEN_TYPE =", value, "tokenType");
            return this;
        }

        public Criteria andTokenTypeNotEqualTo(String value) {
            addCriterion("TOKEN_TYPE <>", value, "tokenType");
            return this;
        }

        public Criteria andTokenTypeGreaterThan(String value) {
            addCriterion("TOKEN_TYPE >", value, "tokenType");
            return this;
        }

        public Criteria andTokenTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TOKEN_TYPE >=", value, "tokenType");
            return this;
        }

        public Criteria andTokenTypeLessThan(String value) {
            addCriterion("TOKEN_TYPE <", value, "tokenType");
            return this;
        }

        public Criteria andTokenTypeLessThanOrEqualTo(String value) {
            addCriterion("TOKEN_TYPE <=", value, "tokenType");
            return this;
        }

        public Criteria andTokenTypeLike(String value) {
            addCriterion("TOKEN_TYPE like", value, "tokenType");
            return this;
        }

        public Criteria andTokenTypeNotLike(String value) {
            addCriterion("TOKEN_TYPE not like", value, "tokenType");
            return this;
        }

        public Criteria andTokenTypeIn(List<String> values) {
            addCriterion("TOKEN_TYPE in", values, "tokenType");
            return this;
        }

        public Criteria andTokenTypeNotIn(List<String> values) {
            addCriterion("TOKEN_TYPE not in", values, "tokenType");
            return this;
        }

        public Criteria andTokenTypeBetween(String value1, String value2) {
            addCriterion("TOKEN_TYPE between", value1, value2, "tokenType");
            return this;
        }

        public Criteria andTokenTypeNotBetween(String value1, String value2) {
            addCriterion("TOKEN_TYPE not between", value1, value2, "tokenType");
            return this;
        }

        public Criteria andExpiresInIsNull() {
            addCriterion("EXPIRES_IN is null");
            return this;
        }

        public Criteria andExpiresInIsNotNull() {
            addCriterion("EXPIRES_IN is not null");
            return this;
        }

        public Criteria andExpiresInEqualTo(Integer value) {
            addCriterion("EXPIRES_IN =", value, "expiresIn");
            return this;
        }

        public Criteria andExpiresInNotEqualTo(Integer value) {
            addCriterion("EXPIRES_IN <>", value, "expiresIn");
            return this;
        }

        public Criteria andExpiresInGreaterThan(Integer value) {
            addCriterion("EXPIRES_IN >", value, "expiresIn");
            return this;
        }

        public Criteria andExpiresInGreaterThanOrEqualTo(Integer value) {
            addCriterion("EXPIRES_IN >=", value, "expiresIn");
            return this;
        }

        public Criteria andExpiresInLessThan(Integer value) {
            addCriterion("EXPIRES_IN <", value, "expiresIn");
            return this;
        }

        public Criteria andExpiresInLessThanOrEqualTo(Integer value) {
            addCriterion("EXPIRES_IN <=", value, "expiresIn");
            return this;
        }

        public Criteria andExpiresInIn(List<Integer> values) {
            addCriterion("EXPIRES_IN in", values, "expiresIn");
            return this;
        }

        public Criteria andExpiresInNotIn(List<Integer> values) {
            addCriterion("EXPIRES_IN not in", values, "expiresIn");
            return this;
        }

        public Criteria andExpiresInBetween(Integer value1, Integer value2) {
            addCriterion("EXPIRES_IN between", value1, value2, "expiresIn");
            return this;
        }

        public Criteria andExpiresInNotBetween(Integer value1, Integer value2) {
            addCriterion("EXPIRES_IN not between", value1, value2, "expiresIn");
            return this;
        }

        public Criteria andRefreshTokenIsNull() {
            addCriterion("REFRESH_TOKEN is null");
            return this;
        }

        public Criteria andRefreshTokenIsNotNull() {
            addCriterion("REFRESH_TOKEN is not null");
            return this;
        }

        public Criteria andRefreshTokenEqualTo(String value) {
            addCriterion("REFRESH_TOKEN =", value, "refreshToken");
            return this;
        }

        public Criteria andRefreshTokenNotEqualTo(String value) {
            addCriterion("REFRESH_TOKEN <>", value, "refreshToken");
            return this;
        }

        public Criteria andRefreshTokenGreaterThan(String value) {
            addCriterion("REFRESH_TOKEN >", value, "refreshToken");
            return this;
        }

        public Criteria andRefreshTokenGreaterThanOrEqualTo(String value) {
            addCriterion("REFRESH_TOKEN >=", value, "refreshToken");
            return this;
        }

        public Criteria andRefreshTokenLessThan(String value) {
            addCriterion("REFRESH_TOKEN <", value, "refreshToken");
            return this;
        }

        public Criteria andRefreshTokenLessThanOrEqualTo(String value) {
            addCriterion("REFRESH_TOKEN <=", value, "refreshToken");
            return this;
        }

        public Criteria andRefreshTokenLike(String value) {
            addCriterion("REFRESH_TOKEN like", value, "refreshToken");
            return this;
        }

        public Criteria andRefreshTokenNotLike(String value) {
            addCriterion("REFRESH_TOKEN not like", value, "refreshToken");
            return this;
        }

        public Criteria andRefreshTokenIn(List<String> values) {
            addCriterion("REFRESH_TOKEN in", values, "refreshToken");
            return this;
        }

        public Criteria andRefreshTokenNotIn(List<String> values) {
            addCriterion("REFRESH_TOKEN not in", values, "refreshToken");
            return this;
        }

        public Criteria andRefreshTokenBetween(String value1, String value2) {
            addCriterion("REFRESH_TOKEN between", value1, value2, "refreshToken");
            return this;
        }

        public Criteria andRefreshTokenNotBetween(String value1, String value2) {
            addCriterion("REFRESH_TOKEN not between", value1, value2, "refreshToken");
            return this;
        }

        public Criteria andReExpiresInIsNull() {
            addCriterion("RE_EXPIRES_IN is null");
            return this;
        }

        public Criteria andReExpiresInIsNotNull() {
            addCriterion("RE_EXPIRES_IN is not null");
            return this;
        }

        public Criteria andReExpiresInEqualTo(Integer value) {
            addCriterion("RE_EXPIRES_IN =", value, "reExpiresIn");
            return this;
        }

        public Criteria andReExpiresInNotEqualTo(Integer value) {
            addCriterion("RE_EXPIRES_IN <>", value, "reExpiresIn");
            return this;
        }

        public Criteria andReExpiresInGreaterThan(Integer value) {
            addCriterion("RE_EXPIRES_IN >", value, "reExpiresIn");
            return this;
        }

        public Criteria andReExpiresInGreaterThanOrEqualTo(Integer value) {
            addCriterion("RE_EXPIRES_IN >=", value, "reExpiresIn");
            return this;
        }

        public Criteria andReExpiresInLessThan(Integer value) {
            addCriterion("RE_EXPIRES_IN <", value, "reExpiresIn");
            return this;
        }

        public Criteria andReExpiresInLessThanOrEqualTo(Integer value) {
            addCriterion("RE_EXPIRES_IN <=", value, "reExpiresIn");
            return this;
        }

        public Criteria andReExpiresInIn(List<Integer> values) {
            addCriterion("RE_EXPIRES_IN in", values, "reExpiresIn");
            return this;
        }

        public Criteria andReExpiresInNotIn(List<Integer> values) {
            addCriterion("RE_EXPIRES_IN not in", values, "reExpiresIn");
            return this;
        }

        public Criteria andReExpiresInBetween(Integer value1, Integer value2) {
            addCriterion("RE_EXPIRES_IN between", value1, value2, "reExpiresIn");
            return this;
        }

        public Criteria andReExpiresInNotBetween(Integer value1, Integer value2) {
            addCriterion("RE_EXPIRES_IN not between", value1, value2, "reExpiresIn");
            return this;
        }

        public Criteria andR1ExpiresInIsNull() {
            addCriterion("R1_EXPIRES_IN is null");
            return this;
        }

        public Criteria andR1ExpiresInIsNotNull() {
            addCriterion("R1_EXPIRES_IN is not null");
            return this;
        }

        public Criteria andR1ExpiresInEqualTo(Integer value) {
            addCriterion("R1_EXPIRES_IN =", value, "r1ExpiresIn");
            return this;
        }

        public Criteria andR1ExpiresInNotEqualTo(Integer value) {
            addCriterion("R1_EXPIRES_IN <>", value, "r1ExpiresIn");
            return this;
        }

        public Criteria andR1ExpiresInGreaterThan(Integer value) {
            addCriterion("R1_EXPIRES_IN >", value, "r1ExpiresIn");
            return this;
        }

        public Criteria andR1ExpiresInGreaterThanOrEqualTo(Integer value) {
            addCriterion("R1_EXPIRES_IN >=", value, "r1ExpiresIn");
            return this;
        }

        public Criteria andR1ExpiresInLessThan(Integer value) {
            addCriterion("R1_EXPIRES_IN <", value, "r1ExpiresIn");
            return this;
        }

        public Criteria andR1ExpiresInLessThanOrEqualTo(Integer value) {
            addCriterion("R1_EXPIRES_IN <=", value, "r1ExpiresIn");
            return this;
        }

        public Criteria andR1ExpiresInIn(List<Integer> values) {
            addCriterion("R1_EXPIRES_IN in", values, "r1ExpiresIn");
            return this;
        }

        public Criteria andR1ExpiresInNotIn(List<Integer> values) {
            addCriterion("R1_EXPIRES_IN not in", values, "r1ExpiresIn");
            return this;
        }

        public Criteria andR1ExpiresInBetween(Integer value1, Integer value2) {
            addCriterion("R1_EXPIRES_IN between", value1, value2, "r1ExpiresIn");
            return this;
        }

        public Criteria andR1ExpiresInNotBetween(Integer value1, Integer value2) {
            addCriterion("R1_EXPIRES_IN not between", value1, value2, "r1ExpiresIn");
            return this;
        }

        public Criteria andR2ExpiresInIsNull() {
            addCriterion("R2_EXPIRES_IN is null");
            return this;
        }

        public Criteria andR2ExpiresInIsNotNull() {
            addCriterion("R2_EXPIRES_IN is not null");
            return this;
        }

        public Criteria andR2ExpiresInEqualTo(Integer value) {
            addCriterion("R2_EXPIRES_IN =", value, "r2ExpiresIn");
            return this;
        }

        public Criteria andR2ExpiresInNotEqualTo(Integer value) {
            addCriterion("R2_EXPIRES_IN <>", value, "r2ExpiresIn");
            return this;
        }

        public Criteria andR2ExpiresInGreaterThan(Integer value) {
            addCriterion("R2_EXPIRES_IN >", value, "r2ExpiresIn");
            return this;
        }

        public Criteria andR2ExpiresInGreaterThanOrEqualTo(Integer value) {
            addCriterion("R2_EXPIRES_IN >=", value, "r2ExpiresIn");
            return this;
        }

        public Criteria andR2ExpiresInLessThan(Integer value) {
            addCriterion("R2_EXPIRES_IN <", value, "r2ExpiresIn");
            return this;
        }

        public Criteria andR2ExpiresInLessThanOrEqualTo(Integer value) {
            addCriterion("R2_EXPIRES_IN <=", value, "r2ExpiresIn");
            return this;
        }

        public Criteria andR2ExpiresInIn(List<Integer> values) {
            addCriterion("R2_EXPIRES_IN in", values, "r2ExpiresIn");
            return this;
        }

        public Criteria andR2ExpiresInNotIn(List<Integer> values) {
            addCriterion("R2_EXPIRES_IN not in", values, "r2ExpiresIn");
            return this;
        }

        public Criteria andR2ExpiresInBetween(Integer value1, Integer value2) {
            addCriterion("R2_EXPIRES_IN between", value1, value2, "r2ExpiresIn");
            return this;
        }

        public Criteria andR2ExpiresInNotBetween(Integer value1, Integer value2) {
            addCriterion("R2_EXPIRES_IN not between", value1, value2, "r2ExpiresIn");
            return this;
        }

        public Criteria andW1ExpiresInIsNull() {
            addCriterion("W1_EXPIRES_IN is null");
            return this;
        }

        public Criteria andW1ExpiresInIsNotNull() {
            addCriterion("W1_EXPIRES_IN is not null");
            return this;
        }

        public Criteria andW1ExpiresInEqualTo(Integer value) {
            addCriterion("W1_EXPIRES_IN =", value, "w1ExpiresIn");
            return this;
        }

        public Criteria andW1ExpiresInNotEqualTo(Integer value) {
            addCriterion("W1_EXPIRES_IN <>", value, "w1ExpiresIn");
            return this;
        }

        public Criteria andW1ExpiresInGreaterThan(Integer value) {
            addCriterion("W1_EXPIRES_IN >", value, "w1ExpiresIn");
            return this;
        }

        public Criteria andW1ExpiresInGreaterThanOrEqualTo(Integer value) {
            addCriterion("W1_EXPIRES_IN >=", value, "w1ExpiresIn");
            return this;
        }

        public Criteria andW1ExpiresInLessThan(Integer value) {
            addCriterion("W1_EXPIRES_IN <", value, "w1ExpiresIn");
            return this;
        }

        public Criteria andW1ExpiresInLessThanOrEqualTo(Integer value) {
            addCriterion("W1_EXPIRES_IN <=", value, "w1ExpiresIn");
            return this;
        }

        public Criteria andW1ExpiresInIn(List<Integer> values) {
            addCriterion("W1_EXPIRES_IN in", values, "w1ExpiresIn");
            return this;
        }

        public Criteria andW1ExpiresInNotIn(List<Integer> values) {
            addCriterion("W1_EXPIRES_IN not in", values, "w1ExpiresIn");
            return this;
        }

        public Criteria andW1ExpiresInBetween(Integer value1, Integer value2) {
            addCriterion("W1_EXPIRES_IN between", value1, value2, "w1ExpiresIn");
            return this;
        }

        public Criteria andW1ExpiresInNotBetween(Integer value1, Integer value2) {
            addCriterion("W1_EXPIRES_IN not between", value1, value2, "w1ExpiresIn");
            return this;
        }

        public Criteria andW2ExpiresInIsNull() {
            addCriterion("W2_EXPIRES_IN is null");
            return this;
        }

        public Criteria andW2ExpiresInIsNotNull() {
            addCriterion("W2_EXPIRES_IN is not null");
            return this;
        }

        public Criteria andW2ExpiresInEqualTo(Integer value) {
            addCriterion("W2_EXPIRES_IN =", value, "w2ExpiresIn");
            return this;
        }

        public Criteria andW2ExpiresInNotEqualTo(Integer value) {
            addCriterion("W2_EXPIRES_IN <>", value, "w2ExpiresIn");
            return this;
        }

        public Criteria andW2ExpiresInGreaterThan(Integer value) {
            addCriterion("W2_EXPIRES_IN >", value, "w2ExpiresIn");
            return this;
        }

        public Criteria andW2ExpiresInGreaterThanOrEqualTo(Integer value) {
            addCriterion("W2_EXPIRES_IN >=", value, "w2ExpiresIn");
            return this;
        }

        public Criteria andW2ExpiresInLessThan(Integer value) {
            addCriterion("W2_EXPIRES_IN <", value, "w2ExpiresIn");
            return this;
        }

        public Criteria andW2ExpiresInLessThanOrEqualTo(Integer value) {
            addCriterion("W2_EXPIRES_IN <=", value, "w2ExpiresIn");
            return this;
        }

        public Criteria andW2ExpiresInIn(List<Integer> values) {
            addCriterion("W2_EXPIRES_IN in", values, "w2ExpiresIn");
            return this;
        }

        public Criteria andW2ExpiresInNotIn(List<Integer> values) {
            addCriterion("W2_EXPIRES_IN not in", values, "w2ExpiresIn");
            return this;
        }

        public Criteria andW2ExpiresInBetween(Integer value1, Integer value2) {
            addCriterion("W2_EXPIRES_IN between", value1, value2, "w2ExpiresIn");
            return this;
        }

        public Criteria andW2ExpiresInNotBetween(Integer value1, Integer value2) {
            addCriterion("W2_EXPIRES_IN not between", value1, value2, "w2ExpiresIn");
            return this;
        }
    }
}