/*
 * Powered By [rapid-framework]
 * Web Site: http://www.rapid-framework.org.cn
 * Google Code: http://code.google.com/p/rapid-framework/
 * Since 2008 - 2014
 */

package com.dream.item.dao;

import org.springframework.stereotype.Repository;

import com.dream.item.model.Item;
import com.dream.item.model.ItemCriteria;
import com.dream.item.vo.query.ItemQuery;
import com.dream.rapid.base.BaseIbatisDao;
import com.dream.rapid.page.Page;
/**
 * @author Frank email:46886799#163.com
 * @version 1.0
 * @since 1.0
 */


@Repository
public class ItemDao extends BaseIbatisDao<Item,java.lang.Integer,ItemCriteria>{
	
	@Override
	public String getIbatisSqlMapNamespace() {
		return "TOP_ITEM";
	}
	
	
	public Page findPage(ItemQuery query) {
		return pageQuery(getIbatisSqlMapNamespace()+".findPage",query);
	}


	@Override
	protected void prepareObjectForSaveOrUpdate(Item source,Item dest) {
		// TODO Auto-generated method stub
		
	}
	

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table TOP_ITEM
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private static class UpdateByCriteriaParms extends ItemCriteria {
        private Object record;

        public UpdateByCriteriaParms(Object record, ItemCriteria criteria) {
            super(criteria);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }


	@Override
	protected ItemCriteria getCriteriaParam(Item record, ItemCriteria criteria) {
		return new UpdateByCriteriaParms(record,criteria);
	}
	

}
