package com.dream.recommend.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class RecommendModeSettingCriteria {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table TOP_RECOMMEND_MODE_SETTING
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table TOP_RECOMMEND_MODE_SETTING
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    protected List oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_RECOMMEND_MODE_SETTING
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public RecommendModeSettingCriteria() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_RECOMMEND_MODE_SETTING
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    protected RecommendModeSettingCriteria(RecommendModeSettingCriteria example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_RECOMMEND_MODE_SETTING
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_RECOMMEND_MODE_SETTING
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_RECOMMEND_MODE_SETTING
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_RECOMMEND_MODE_SETTING
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_RECOMMEND_MODE_SETTING
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_RECOMMEND_MODE_SETTING
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_RECOMMEND_MODE_SETTING
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table TOP_RECOMMEND_MODE_SETTING
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andShopIdIsNull() {
            addCriterion("SHOP_ID is null");
            return this;
        }

        public Criteria andShopIdIsNotNull() {
            addCriterion("SHOP_ID is not null");
            return this;
        }

        public Criteria andShopIdEqualTo(Long value) {
            addCriterion("SHOP_ID =", value, "shopId");
            return this;
        }

        public Criteria andShopIdNotEqualTo(Long value) {
            addCriterion("SHOP_ID <>", value, "shopId");
            return this;
        }

        public Criteria andShopIdGreaterThan(Long value) {
            addCriterion("SHOP_ID >", value, "shopId");
            return this;
        }

        public Criteria andShopIdGreaterThanOrEqualTo(Long value) {
            addCriterion("SHOP_ID >=", value, "shopId");
            return this;
        }

        public Criteria andShopIdLessThan(Long value) {
            addCriterion("SHOP_ID <", value, "shopId");
            return this;
        }

        public Criteria andShopIdLessThanOrEqualTo(Long value) {
            addCriterion("SHOP_ID <=", value, "shopId");
            return this;
        }

        public Criteria andShopIdIn(List values) {
            addCriterion("SHOP_ID in", values, "shopId");
            return this;
        }

        public Criteria andShopIdNotIn(List values) {
            addCriterion("SHOP_ID not in", values, "shopId");
            return this;
        }

        public Criteria andShopIdBetween(Long value1, Long value2) {
            addCriterion("SHOP_ID between", value1, value2, "shopId");
            return this;
        }

        public Criteria andShopIdNotBetween(Long value1, Long value2) {
            addCriterion("SHOP_ID not between", value1, value2, "shopId");
            return this;
        }

        public Criteria andIsSaledFirstIsNull() {
            addCriterion("IS_SALED_FIRST is null");
            return this;
        }

        public Criteria andIsSaledFirstIsNotNull() {
            addCriterion("IS_SALED_FIRST is not null");
            return this;
        }

        public Criteria andIsSaledFirstEqualTo(String value) {
            addCriterion("IS_SALED_FIRST =", value, "isSaledFirst");
            return this;
        }

        public Criteria andIsSaledFirstNotEqualTo(String value) {
            addCriterion("IS_SALED_FIRST <>", value, "isSaledFirst");
            return this;
        }

        public Criteria andIsSaledFirstGreaterThan(String value) {
            addCriterion("IS_SALED_FIRST >", value, "isSaledFirst");
            return this;
        }

        public Criteria andIsSaledFirstGreaterThanOrEqualTo(String value) {
            addCriterion("IS_SALED_FIRST >=", value, "isSaledFirst");
            return this;
        }

        public Criteria andIsSaledFirstLessThan(String value) {
            addCriterion("IS_SALED_FIRST <", value, "isSaledFirst");
            return this;
        }

        public Criteria andIsSaledFirstLessThanOrEqualTo(String value) {
            addCriterion("IS_SALED_FIRST <=", value, "isSaledFirst");
            return this;
        }

        public Criteria andIsSaledFirstLike(String value) {
            addCriterion("IS_SALED_FIRST like", value, "isSaledFirst");
            return this;
        }

        public Criteria andIsSaledFirstNotLike(String value) {
            addCriterion("IS_SALED_FIRST not like", value, "isSaledFirst");
            return this;
        }

        public Criteria andIsSaledFirstIn(List values) {
            addCriterion("IS_SALED_FIRST in", values, "isSaledFirst");
            return this;
        }

        public Criteria andIsSaledFirstNotIn(List values) {
            addCriterion("IS_SALED_FIRST not in", values, "isSaledFirst");
            return this;
        }

        public Criteria andIsSaledFirstBetween(String value1, String value2) {
            addCriterion("IS_SALED_FIRST between", value1, value2, "isSaledFirst");
            return this;
        }

        public Criteria andIsSaledFirstNotBetween(String value1, String value2) {
            addCriterion("IS_SALED_FIRST not between", value1, value2, "isSaledFirst");
            return this;
        }

        public Criteria andSaledNumIsNull() {
            addCriterion("SALED_NUM is null");
            return this;
        }

        public Criteria andSaledNumIsNotNull() {
            addCriterion("SALED_NUM is not null");
            return this;
        }

        public Criteria andSaledNumEqualTo(Integer value) {
            addCriterion("SALED_NUM =", value, "saledNum");
            return this;
        }

        public Criteria andSaledNumNotEqualTo(Integer value) {
            addCriterion("SALED_NUM <>", value, "saledNum");
            return this;
        }

        public Criteria andSaledNumGreaterThan(Integer value) {
            addCriterion("SALED_NUM >", value, "saledNum");
            return this;
        }

        public Criteria andSaledNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("SALED_NUM >=", value, "saledNum");
            return this;
        }

        public Criteria andSaledNumLessThan(Integer value) {
            addCriterion("SALED_NUM <", value, "saledNum");
            return this;
        }

        public Criteria andSaledNumLessThanOrEqualTo(Integer value) {
            addCriterion("SALED_NUM <=", value, "saledNum");
            return this;
        }

        public Criteria andSaledNumIn(List values) {
            addCriterion("SALED_NUM in", values, "saledNum");
            return this;
        }

        public Criteria andSaledNumNotIn(List values) {
            addCriterion("SALED_NUM not in", values, "saledNum");
            return this;
        }

        public Criteria andSaledNumBetween(Integer value1, Integer value2) {
            addCriterion("SALED_NUM between", value1, value2, "saledNum");
            return this;
        }

        public Criteria andSaledNumNotBetween(Integer value1, Integer value2) {
            addCriterion("SALED_NUM not between", value1, value2, "saledNum");
            return this;
        }

        public Criteria andIsStorageFilteredIsNull() {
            addCriterion("IS_STORAGE_FILTERED is null");
            return this;
        }

        public Criteria andIsStorageFilteredIsNotNull() {
            addCriterion("IS_STORAGE_FILTERED is not null");
            return this;
        }

        public Criteria andIsStorageFilteredEqualTo(String value) {
            addCriterion("IS_STORAGE_FILTERED =", value, "isStorageFiltered");
            return this;
        }

        public Criteria andIsStorageFilteredNotEqualTo(String value) {
            addCriterion("IS_STORAGE_FILTERED <>", value, "isStorageFiltered");
            return this;
        }

        public Criteria andIsStorageFilteredGreaterThan(String value) {
            addCriterion("IS_STORAGE_FILTERED >", value, "isStorageFiltered");
            return this;
        }

        public Criteria andIsStorageFilteredGreaterThanOrEqualTo(String value) {
            addCriterion("IS_STORAGE_FILTERED >=", value, "isStorageFiltered");
            return this;
        }

        public Criteria andIsStorageFilteredLessThan(String value) {
            addCriterion("IS_STORAGE_FILTERED <", value, "isStorageFiltered");
            return this;
        }

        public Criteria andIsStorageFilteredLessThanOrEqualTo(String value) {
            addCriterion("IS_STORAGE_FILTERED <=", value, "isStorageFiltered");
            return this;
        }

        public Criteria andIsStorageFilteredLike(String value) {
            addCriterion("IS_STORAGE_FILTERED like", value, "isStorageFiltered");
            return this;
        }

        public Criteria andIsStorageFilteredNotLike(String value) {
            addCriterion("IS_STORAGE_FILTERED not like", value, "isStorageFiltered");
            return this;
        }

        public Criteria andIsStorageFilteredIn(List values) {
            addCriterion("IS_STORAGE_FILTERED in", values, "isStorageFiltered");
            return this;
        }

        public Criteria andIsStorageFilteredNotIn(List values) {
            addCriterion("IS_STORAGE_FILTERED not in", values, "isStorageFiltered");
            return this;
        }

        public Criteria andIsStorageFilteredBetween(String value1, String value2) {
            addCriterion("IS_STORAGE_FILTERED between", value1, value2, "isStorageFiltered");
            return this;
        }

        public Criteria andIsStorageFilteredNotBetween(String value1, String value2) {
            addCriterion("IS_STORAGE_FILTERED not between", value1, value2, "isStorageFiltered");
            return this;
        }

        public Criteria andStorageNumIsNull() {
            addCriterion("STORAGE_NUM is null");
            return this;
        }

        public Criteria andStorageNumIsNotNull() {
            addCriterion("STORAGE_NUM is not null");
            return this;
        }

        public Criteria andStorageNumEqualTo(String value) {
            addCriterion("STORAGE_NUM =", value, "storageNum");
            return this;
        }

        public Criteria andStorageNumNotEqualTo(String value) {
            addCriterion("STORAGE_NUM <>", value, "storageNum");
            return this;
        }

        public Criteria andStorageNumGreaterThan(String value) {
            addCriterion("STORAGE_NUM >", value, "storageNum");
            return this;
        }

        public Criteria andStorageNumGreaterThanOrEqualTo(String value) {
            addCriterion("STORAGE_NUM >=", value, "storageNum");
            return this;
        }

        public Criteria andStorageNumLessThan(String value) {
            addCriterion("STORAGE_NUM <", value, "storageNum");
            return this;
        }

        public Criteria andStorageNumLessThanOrEqualTo(String value) {
            addCriterion("STORAGE_NUM <=", value, "storageNum");
            return this;
        }

        public Criteria andStorageNumLike(String value) {
            addCriterion("STORAGE_NUM like", value, "storageNum");
            return this;
        }

        public Criteria andStorageNumNotLike(String value) {
            addCriterion("STORAGE_NUM not like", value, "storageNum");
            return this;
        }

        public Criteria andStorageNumIn(List values) {
            addCriterion("STORAGE_NUM in", values, "storageNum");
            return this;
        }

        public Criteria andStorageNumNotIn(List values) {
            addCriterion("STORAGE_NUM not in", values, "storageNum");
            return this;
        }

        public Criteria andStorageNumBetween(String value1, String value2) {
            addCriterion("STORAGE_NUM between", value1, value2, "storageNum");
            return this;
        }

        public Criteria andStorageNumNotBetween(String value1, String value2) {
            addCriterion("STORAGE_NUM not between", value1, value2, "storageNum");
            return this;
        }

        public Criteria andIsOffshelvesFilteredIsNull() {
            addCriterion("IS_OFFSHELVES_FILTERED is null");
            return this;
        }

        public Criteria andIsOffshelvesFilteredIsNotNull() {
            addCriterion("IS_OFFSHELVES_FILTERED is not null");
            return this;
        }

        public Criteria andIsOffshelvesFilteredEqualTo(String value) {
            addCriterion("IS_OFFSHELVES_FILTERED =", value, "isOffshelvesFiltered");
            return this;
        }

        public Criteria andIsOffshelvesFilteredNotEqualTo(String value) {
            addCriterion("IS_OFFSHELVES_FILTERED <>", value, "isOffshelvesFiltered");
            return this;
        }

        public Criteria andIsOffshelvesFilteredGreaterThan(String value) {
            addCriterion("IS_OFFSHELVES_FILTERED >", value, "isOffshelvesFiltered");
            return this;
        }

        public Criteria andIsOffshelvesFilteredGreaterThanOrEqualTo(String value) {
            addCriterion("IS_OFFSHELVES_FILTERED >=", value, "isOffshelvesFiltered");
            return this;
        }

        public Criteria andIsOffshelvesFilteredLessThan(String value) {
            addCriterion("IS_OFFSHELVES_FILTERED <", value, "isOffshelvesFiltered");
            return this;
        }

        public Criteria andIsOffshelvesFilteredLessThanOrEqualTo(String value) {
            addCriterion("IS_OFFSHELVES_FILTERED <=", value, "isOffshelvesFiltered");
            return this;
        }

        public Criteria andIsOffshelvesFilteredLike(String value) {
            addCriterion("IS_OFFSHELVES_FILTERED like", value, "isOffshelvesFiltered");
            return this;
        }

        public Criteria andIsOffshelvesFilteredNotLike(String value) {
            addCriterion("IS_OFFSHELVES_FILTERED not like", value, "isOffshelvesFiltered");
            return this;
        }

        public Criteria andIsOffshelvesFilteredIn(List values) {
            addCriterion("IS_OFFSHELVES_FILTERED in", values, "isOffshelvesFiltered");
            return this;
        }

        public Criteria andIsOffshelvesFilteredNotIn(List values) {
            addCriterion("IS_OFFSHELVES_FILTERED not in", values, "isOffshelvesFiltered");
            return this;
        }

        public Criteria andIsOffshelvesFilteredBetween(String value1, String value2) {
            addCriterion("IS_OFFSHELVES_FILTERED between", value1, value2, "isOffshelvesFiltered");
            return this;
        }

        public Criteria andIsOffshelvesFilteredNotBetween(String value1, String value2) {
            addCriterion("IS_OFFSHELVES_FILTERED not between", value1, value2, "isOffshelvesFiltered");
            return this;
        }

        public Criteria andOffshelvesTimeIsNull() {
            addCriterion("OFFSHELVES_TIME is null");
            return this;
        }

        public Criteria andOffshelvesTimeIsNotNull() {
            addCriterion("OFFSHELVES_TIME is not null");
            return this;
        }

        public Criteria andOffshelvesTimeEqualTo(Integer value) {
            addCriterion("OFFSHELVES_TIME =", value, "offshelvesTime");
            return this;
        }

        public Criteria andOffshelvesTimeNotEqualTo(Integer value) {
            addCriterion("OFFSHELVES_TIME <>", value, "offshelvesTime");
            return this;
        }

        public Criteria andOffshelvesTimeGreaterThan(Integer value) {
            addCriterion("OFFSHELVES_TIME >", value, "offshelvesTime");
            return this;
        }

        public Criteria andOffshelvesTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("OFFSHELVES_TIME >=", value, "offshelvesTime");
            return this;
        }

        public Criteria andOffshelvesTimeLessThan(Integer value) {
            addCriterion("OFFSHELVES_TIME <", value, "offshelvesTime");
            return this;
        }

        public Criteria andOffshelvesTimeLessThanOrEqualTo(Integer value) {
            addCriterion("OFFSHELVES_TIME <=", value, "offshelvesTime");
            return this;
        }

        public Criteria andOffshelvesTimeIn(List values) {
            addCriterion("OFFSHELVES_TIME in", values, "offshelvesTime");
            return this;
        }

        public Criteria andOffshelvesTimeNotIn(List values) {
            addCriterion("OFFSHELVES_TIME not in", values, "offshelvesTime");
            return this;
        }

        public Criteria andOffshelvesTimeBetween(Integer value1, Integer value2) {
            addCriterion("OFFSHELVES_TIME between", value1, value2, "offshelvesTime");
            return this;
        }

        public Criteria andOffshelvesTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("OFFSHELVES_TIME not between", value1, value2, "offshelvesTime");
            return this;
        }

        public Criteria andIsOnshelvesFilteredIsNull() {
            addCriterion("IS_ONSHELVES_FILTERED is null");
            return this;
        }

        public Criteria andIsOnshelvesFilteredIsNotNull() {
            addCriterion("IS_ONSHELVES_FILTERED is not null");
            return this;
        }

        public Criteria andIsOnshelvesFilteredEqualTo(String value) {
            addCriterion("IS_ONSHELVES_FILTERED =", value, "isOnshelvesFiltered");
            return this;
        }

        public Criteria andIsOnshelvesFilteredNotEqualTo(String value) {
            addCriterion("IS_ONSHELVES_FILTERED <>", value, "isOnshelvesFiltered");
            return this;
        }

        public Criteria andIsOnshelvesFilteredGreaterThan(String value) {
            addCriterion("IS_ONSHELVES_FILTERED >", value, "isOnshelvesFiltered");
            return this;
        }

        public Criteria andIsOnshelvesFilteredGreaterThanOrEqualTo(String value) {
            addCriterion("IS_ONSHELVES_FILTERED >=", value, "isOnshelvesFiltered");
            return this;
        }

        public Criteria andIsOnshelvesFilteredLessThan(String value) {
            addCriterion("IS_ONSHELVES_FILTERED <", value, "isOnshelvesFiltered");
            return this;
        }

        public Criteria andIsOnshelvesFilteredLessThanOrEqualTo(String value) {
            addCriterion("IS_ONSHELVES_FILTERED <=", value, "isOnshelvesFiltered");
            return this;
        }

        public Criteria andIsOnshelvesFilteredLike(String value) {
            addCriterion("IS_ONSHELVES_FILTERED like", value, "isOnshelvesFiltered");
            return this;
        }

        public Criteria andIsOnshelvesFilteredNotLike(String value) {
            addCriterion("IS_ONSHELVES_FILTERED not like", value, "isOnshelvesFiltered");
            return this;
        }

        public Criteria andIsOnshelvesFilteredIn(List values) {
            addCriterion("IS_ONSHELVES_FILTERED in", values, "isOnshelvesFiltered");
            return this;
        }

        public Criteria andIsOnshelvesFilteredNotIn(List values) {
            addCriterion("IS_ONSHELVES_FILTERED not in", values, "isOnshelvesFiltered");
            return this;
        }

        public Criteria andIsOnshelvesFilteredBetween(String value1, String value2) {
            addCriterion("IS_ONSHELVES_FILTERED between", value1, value2, "isOnshelvesFiltered");
            return this;
        }

        public Criteria andIsOnshelvesFilteredNotBetween(String value1, String value2) {
            addCriterion("IS_ONSHELVES_FILTERED not between", value1, value2, "isOnshelvesFiltered");
            return this;
        }

        public Criteria andLastModifiedByIsNull() {
            addCriterion("LAST_MODIFIED_BY is null");
            return this;
        }

        public Criteria andLastModifiedByIsNotNull() {
            addCriterion("LAST_MODIFIED_BY is not null");
            return this;
        }

        public Criteria andLastModifiedByEqualTo(String value) {
            addCriterion("LAST_MODIFIED_BY =", value, "lastModifiedBy");
            return this;
        }

        public Criteria andLastModifiedByNotEqualTo(String value) {
            addCriterion("LAST_MODIFIED_BY <>", value, "lastModifiedBy");
            return this;
        }

        public Criteria andLastModifiedByGreaterThan(String value) {
            addCriterion("LAST_MODIFIED_BY >", value, "lastModifiedBy");
            return this;
        }

        public Criteria andLastModifiedByGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_MODIFIED_BY >=", value, "lastModifiedBy");
            return this;
        }

        public Criteria andLastModifiedByLessThan(String value) {
            addCriterion("LAST_MODIFIED_BY <", value, "lastModifiedBy");
            return this;
        }

        public Criteria andLastModifiedByLessThanOrEqualTo(String value) {
            addCriterion("LAST_MODIFIED_BY <=", value, "lastModifiedBy");
            return this;
        }

        public Criteria andLastModifiedByLike(String value) {
            addCriterion("LAST_MODIFIED_BY like", value, "lastModifiedBy");
            return this;
        }

        public Criteria andLastModifiedByNotLike(String value) {
            addCriterion("LAST_MODIFIED_BY not like", value, "lastModifiedBy");
            return this;
        }

        public Criteria andLastModifiedByIn(List values) {
            addCriterion("LAST_MODIFIED_BY in", values, "lastModifiedBy");
            return this;
        }

        public Criteria andLastModifiedByNotIn(List values) {
            addCriterion("LAST_MODIFIED_BY not in", values, "lastModifiedBy");
            return this;
        }

        public Criteria andLastModifiedByBetween(String value1, String value2) {
            addCriterion("LAST_MODIFIED_BY between", value1, value2, "lastModifiedBy");
            return this;
        }

        public Criteria andLastModifiedByNotBetween(String value1, String value2) {
            addCriterion("LAST_MODIFIED_BY not between", value1, value2, "lastModifiedBy");
            return this;
        }

        public Criteria andLastModifiedTimeIsNull() {
            addCriterion("LAST_MODIFIED_TIME is null");
            return this;
        }

        public Criteria andLastModifiedTimeIsNotNull() {
            addCriterion("LAST_MODIFIED_TIME is not null");
            return this;
        }

        public Criteria andLastModifiedTimeEqualTo(Date value) {
            addCriterion("LAST_MODIFIED_TIME =", value, "lastModifiedTime");
            return this;
        }

        public Criteria andLastModifiedTimeNotEqualTo(Date value) {
            addCriterion("LAST_MODIFIED_TIME <>", value, "lastModifiedTime");
            return this;
        }

        public Criteria andLastModifiedTimeGreaterThan(Date value) {
            addCriterion("LAST_MODIFIED_TIME >", value, "lastModifiedTime");
            return this;
        }

        public Criteria andLastModifiedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_MODIFIED_TIME >=", value, "lastModifiedTime");
            return this;
        }

        public Criteria andLastModifiedTimeLessThan(Date value) {
            addCriterion("LAST_MODIFIED_TIME <", value, "lastModifiedTime");
            return this;
        }

        public Criteria andLastModifiedTimeLessThanOrEqualTo(Date value) {
            addCriterion("LAST_MODIFIED_TIME <=", value, "lastModifiedTime");
            return this;
        }

        public Criteria andLastModifiedTimeIn(List values) {
            addCriterion("LAST_MODIFIED_TIME in", values, "lastModifiedTime");
            return this;
        }

        public Criteria andLastModifiedTimeNotIn(List values) {
            addCriterion("LAST_MODIFIED_TIME not in", values, "lastModifiedTime");
            return this;
        }

        public Criteria andLastModifiedTimeBetween(Date value1, Date value2) {
            addCriterion("LAST_MODIFIED_TIME between", value1, value2, "lastModifiedTime");
            return this;
        }

        public Criteria andLastModifiedTimeNotBetween(Date value1, Date value2) {
            addCriterion("LAST_MODIFIED_TIME not between", value1, value2, "lastModifiedTime");
            return this;
        }
    }
}