package com.dream.recommend.model;

import java.io.Serializable;

public class RecommendLog implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_LOG.ID
     *
     *  Mon Sep 29 17:59:35 CST 2014
     */
    private Object id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_LOG.SHOP_ID
     *
     *  Mon Sep 29 17:59:35 CST 2014
     */
    private Object shopId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_LOG.ITEM_ID
     *
     *  Mon Sep 29 17:59:35 CST 2014
     */
    private Object itemId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_LOG.ITEM_NAME
     *
     *  Mon Sep 29 17:59:35 CST 2014
     */
    private Object itemName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_LOG.LAST_MODIFIED_TIME
     *
     *  Mon Sep 29 17:59:35 CST 2014
     */
    private Object lastModifiedTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table TOP_RECOMMEND_LOG
     *
     *  Mon Sep 29 17:59:35 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_LOG.ID
     *
     * @return the value of TOP_RECOMMEND_LOG.ID
     *
     *  Mon Sep 29 17:59:35 CST 2014
     */
    public Object getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_LOG.ID
     *
     * @param id the value for TOP_RECOMMEND_LOG.ID
     *
     *  Mon Sep 29 17:59:35 CST 2014
     */
    public void setId(Object id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_LOG.SHOP_ID
     *
     * @return the value of TOP_RECOMMEND_LOG.SHOP_ID
     *
     *  Mon Sep 29 17:59:35 CST 2014
     */
    public Object getShopId() {
        return shopId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_LOG.SHOP_ID
     *
     * @param shopId the value for TOP_RECOMMEND_LOG.SHOP_ID
     *
     *  Mon Sep 29 17:59:35 CST 2014
     */
    public void setShopId(Object shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_LOG.ITEM_ID
     *
     * @return the value of TOP_RECOMMEND_LOG.ITEM_ID
     *
     *  Mon Sep 29 17:59:35 CST 2014
     */
    public Object getItemId() {
        return itemId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_LOG.ITEM_ID
     *
     * @param itemId the value for TOP_RECOMMEND_LOG.ITEM_ID
     *
     *  Mon Sep 29 17:59:35 CST 2014
     */
    public void setItemId(Object itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_LOG.ITEM_NAME
     *
     * @return the value of TOP_RECOMMEND_LOG.ITEM_NAME
     *
     *  Mon Sep 29 17:59:35 CST 2014
     */
    public Object getItemName() {
        return itemName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_LOG.ITEM_NAME
     *
     * @param itemName the value for TOP_RECOMMEND_LOG.ITEM_NAME
     *
     *  Mon Sep 29 17:59:35 CST 2014
     */
    public void setItemName(Object itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_LOG.LAST_MODIFIED_TIME
     *
     * @return the value of TOP_RECOMMEND_LOG.LAST_MODIFIED_TIME
     *
     *  Mon Sep 29 17:59:35 CST 2014
     */
    public Object getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_LOG.LAST_MODIFIED_TIME
     *
     * @param lastModifiedTime the value for TOP_RECOMMEND_LOG.LAST_MODIFIED_TIME
     *
     *  Mon Sep 29 17:59:35 CST 2014
     */
    public void setLastModifiedTime(Object lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_RECOMMEND_LOG
     *
     *  Mon Sep 29 17:59:35 CST 2014
     */
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof RecommendLog)) {
            return false;
        }
        RecommendLog other = (RecommendLog) that;
        return this.getId() == null ? other == null : this.getId().equals(other.getId())
            && this.getShopId() == null ? other == null : this.getShopId().equals(other.getShopId())
            && this.getItemId() == null ? other == null : this.getItemId().equals(other.getItemId())
            && this.getItemName() == null ? other == null : this.getItemName().equals(other.getItemName())
            && this.getLastModifiedTime() == null ? other == null : this.getLastModifiedTime().equals(other.getLastModifiedTime());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_RECOMMEND_LOG
     *
     *  Mon Sep 29 17:59:35 CST 2014
     */
    public int hashCode() {
        int hash = 23;
        if (getId() != null) {
            hash *= getId().hashCode();
        }
        if (getShopId() != null) {
            hash *= getShopId().hashCode();
        }
        if (getItemId() != null) {
            hash *= getItemId().hashCode();
        }
        if (getItemName() != null) {
            hash *= getItemName().hashCode();
        }
        if (getLastModifiedTime() != null) {
            hash *= getLastModifiedTime().hashCode();
        }
        return hash;
    }
}