package com.dream.recommend.model;

import java.io.Serializable;
import java.util.Date;

public class RecommendModeSetting implements Serializable {
	
	
	
	public RecommendModeSetting(){
		
	}
	
	
	public RecommendModeSetting(Long id){
		this.shopId = id;
	}
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_MODE_SETTING.SHOP_ID
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    private Long shopId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_MODE_SETTING.IS_SALED_FIRST
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    private String isSaledFirst;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_MODE_SETTING.SALED_NUM
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    private Integer saledNum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_MODE_SETTING.IS_STORAGE_FILTERED
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    private String isStorageFiltered;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_MODE_SETTING.STORAGE_NUM
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    private String storageNum;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_MODE_SETTING.IS_OFFSHELVES_FILTERED
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    private String isOffshelvesFiltered;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_MODE_SETTING.OFFSHELVES_TIME
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    private Integer offshelvesTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_MODE_SETTING.IS_ONSHELVES_FILTERED
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    private String isOnshelvesFiltered;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_MODE_SETTING.LAST_MODIFIED_BY
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    private String lastModifiedBy;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_MODE_SETTING.LAST_MODIFIED_TIME
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    private Date lastModifiedTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table TOP_RECOMMEND_MODE_SETTING
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_MODE_SETTING.SHOP_ID
     *
     * @return the value of TOP_RECOMMEND_MODE_SETTING.SHOP_ID
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_MODE_SETTING.SHOP_ID
     *
     * @param shopId the value for TOP_RECOMMEND_MODE_SETTING.SHOP_ID
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_MODE_SETTING.IS_SALED_FIRST
     *
     * @return the value of TOP_RECOMMEND_MODE_SETTING.IS_SALED_FIRST
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public String getIsSaledFirst() {
        return isSaledFirst;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_MODE_SETTING.IS_SALED_FIRST
     *
     * @param isSaledFirst the value for TOP_RECOMMEND_MODE_SETTING.IS_SALED_FIRST
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public void setIsSaledFirst(String isSaledFirst) {
        this.isSaledFirst = isSaledFirst == null ? null : isSaledFirst.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_MODE_SETTING.SALED_NUM
     *
     * @return the value of TOP_RECOMMEND_MODE_SETTING.SALED_NUM
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public Integer getSaledNum() {
        return saledNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_MODE_SETTING.SALED_NUM
     *
     * @param saledNum the value for TOP_RECOMMEND_MODE_SETTING.SALED_NUM
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public void setSaledNum(Integer saledNum) {
        this.saledNum = saledNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_MODE_SETTING.IS_STORAGE_FILTERED
     *
     * @return the value of TOP_RECOMMEND_MODE_SETTING.IS_STORAGE_FILTERED
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public String getIsStorageFiltered() {
        return isStorageFiltered;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_MODE_SETTING.IS_STORAGE_FILTERED
     *
     * @param isStorageFiltered the value for TOP_RECOMMEND_MODE_SETTING.IS_STORAGE_FILTERED
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public void setIsStorageFiltered(String isStorageFiltered) {
        this.isStorageFiltered = isStorageFiltered == null ? null : isStorageFiltered.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_MODE_SETTING.STORAGE_NUM
     *
     * @return the value of TOP_RECOMMEND_MODE_SETTING.STORAGE_NUM
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public String getStorageNum() {
        return storageNum;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_MODE_SETTING.STORAGE_NUM
     *
     * @param storageNum the value for TOP_RECOMMEND_MODE_SETTING.STORAGE_NUM
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public void setStorageNum(String storageNum) {
        this.storageNum = storageNum == null ? null : storageNum.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_MODE_SETTING.IS_OFFSHELVES_FILTERED
     *
     * @return the value of TOP_RECOMMEND_MODE_SETTING.IS_OFFSHELVES_FILTERED
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public String getIsOffshelvesFiltered() {
        return isOffshelvesFiltered;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_MODE_SETTING.IS_OFFSHELVES_FILTERED
     *
     * @param isOffshelvesFiltered the value for TOP_RECOMMEND_MODE_SETTING.IS_OFFSHELVES_FILTERED
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public void setIsOffshelvesFiltered(String isOffshelvesFiltered) {
        this.isOffshelvesFiltered = isOffshelvesFiltered == null ? null : isOffshelvesFiltered.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_MODE_SETTING.OFFSHELVES_TIME
     *
     * @return the value of TOP_RECOMMEND_MODE_SETTING.OFFSHELVES_TIME
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public Integer getOffshelvesTime() {
        return offshelvesTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_MODE_SETTING.OFFSHELVES_TIME
     *
     * @param offshelvesTime the value for TOP_RECOMMEND_MODE_SETTING.OFFSHELVES_TIME
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public void setOffshelvesTime(Integer offshelvesTime) {
        this.offshelvesTime = offshelvesTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_MODE_SETTING.IS_ONSHELVES_FILTERED
     *
     * @return the value of TOP_RECOMMEND_MODE_SETTING.IS_ONSHELVES_FILTERED
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public String getIsOnshelvesFiltered() {
        return isOnshelvesFiltered;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_MODE_SETTING.IS_ONSHELVES_FILTERED
     *
     * @param isOnshelvesFiltered the value for TOP_RECOMMEND_MODE_SETTING.IS_ONSHELVES_FILTERED
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public void setIsOnshelvesFiltered(String isOnshelvesFiltered) {
        this.isOnshelvesFiltered = isOnshelvesFiltered == null ? null : isOnshelvesFiltered.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_MODE_SETTING.LAST_MODIFIED_BY
     *
     * @return the value of TOP_RECOMMEND_MODE_SETTING.LAST_MODIFIED_BY
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_MODE_SETTING.LAST_MODIFIED_BY
     *
     * @param lastModifiedBy the value for TOP_RECOMMEND_MODE_SETTING.LAST_MODIFIED_BY
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy == null ? null : lastModifiedBy.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_MODE_SETTING.LAST_MODIFIED_TIME
     *
     * @return the value of TOP_RECOMMEND_MODE_SETTING.LAST_MODIFIED_TIME
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public Date getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_MODE_SETTING.LAST_MODIFIED_TIME
     *
     * @param lastModifiedTime the value for TOP_RECOMMEND_MODE_SETTING.LAST_MODIFIED_TIME
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public void setLastModifiedTime(Date lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_RECOMMEND_MODE_SETTING
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof RecommendModeSetting)) {
            return false;
        }
        RecommendModeSetting other = (RecommendModeSetting) that;
        return this.getShopId() == null ? other == null : this.getShopId().equals(other.getShopId())
            && this.getIsSaledFirst() == null ? other == null : this.getIsSaledFirst().equals(other.getIsSaledFirst())
            && this.getSaledNum() == null ? other == null : this.getSaledNum().equals(other.getSaledNum())
            && this.getIsStorageFiltered() == null ? other == null : this.getIsStorageFiltered().equals(other.getIsStorageFiltered())
            && this.getStorageNum() == null ? other == null : this.getStorageNum().equals(other.getStorageNum())
            && this.getIsOffshelvesFiltered() == null ? other == null : this.getIsOffshelvesFiltered().equals(other.getIsOffshelvesFiltered())
            && this.getOffshelvesTime() == null ? other == null : this.getOffshelvesTime().equals(other.getOffshelvesTime())
            && this.getIsOnshelvesFiltered() == null ? other == null : this.getIsOnshelvesFiltered().equals(other.getIsOnshelvesFiltered())
            && this.getLastModifiedBy() == null ? other == null : this.getLastModifiedBy().equals(other.getLastModifiedBy())
            && this.getLastModifiedTime() == null ? other == null : this.getLastModifiedTime().equals(other.getLastModifiedTime());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_RECOMMEND_MODE_SETTING
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    public int hashCode() {
        int hash = 23;
        if (getShopId() != null) {
            hash *= getShopId().hashCode();
        }
        if (getIsSaledFirst() != null) {
            hash *= getIsSaledFirst().hashCode();
        }
        if (getSaledNum() != null) {
            hash *= getSaledNum().hashCode();
        }
        if (getIsStorageFiltered() != null) {
            hash *= getIsStorageFiltered().hashCode();
        }
        if (getStorageNum() != null) {
            hash *= getStorageNum().hashCode();
        }
        if (getIsOffshelvesFiltered() != null) {
            hash *= getIsOffshelvesFiltered().hashCode();
        }
        if (getOffshelvesTime() != null) {
            hash *= getOffshelvesTime().hashCode();
        }
        if (getIsOnshelvesFiltered() != null) {
            hash *= getIsOnshelvesFiltered().hashCode();
        }
        if (getLastModifiedBy() != null) {
            hash *= getLastModifiedBy().hashCode();
        }
        if (getLastModifiedTime() != null) {
            hash *= getLastModifiedTime().hashCode();
        }
        return hash;
    }
}