package com.dream.recommend.model;

import java.io.Serializable;
import java.util.Date;

public class RecommendScopeSetting implements Serializable {
	
	
	public RecommendScopeSetting(){
		
	}
	
	public RecommendScopeSetting(Long shopId){
		this.shopId = shopId;
	}
	
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_SCOPE_SETTING.SHOP_ID
     *
     *  Mon Sep 29 17:58:40 CST 2014
     */
    private Long shopId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_SCOPE_SETTING.SCOPE_TYPE
     *
     *  Mon Sep 29 17:58:40 CST 2014
     */
    private String scopeType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_SCOPE_SETTING.IS_ENABLED
     *
     *  Mon Sep 29 17:58:40 CST 2014
     */
    private String isEnabled;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_SCOPE_SETTING.LAST_MODIFIED_BY
     *
     *  Mon Sep 29 17:58:40 CST 2014
     */
    private Long lastModifiedBy;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_SCOPE_SETTING.LAST_MODIFIED_TIME
     *
     *  Mon Sep 29 17:58:40 CST 2014
     */
    private Date lastModifiedTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table TOP_RECOMMEND_SCOPE_SETTING
     *
     *  Mon Sep 29 17:58:40 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_SCOPE_SETTING.SHOP_ID
     *
     * @return the value of TOP_RECOMMEND_SCOPE_SETTING.SHOP_ID
     *
     *  Mon Sep 29 17:58:40 CST 2014
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_SCOPE_SETTING.SHOP_ID
     *
     * @param shopId the value for TOP_RECOMMEND_SCOPE_SETTING.SHOP_ID
     *
     *  Mon Sep 29 17:58:40 CST 2014
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_SCOPE_SETTING.SCOPE_TYPE
     *
     * @return the value of TOP_RECOMMEND_SCOPE_SETTING.SCOPE_TYPE
     *
     *  Mon Sep 29 17:58:40 CST 2014
     */
    public String getScopeType() {
        return scopeType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_SCOPE_SETTING.SCOPE_TYPE
     *
     * @param scopeType the value for TOP_RECOMMEND_SCOPE_SETTING.SCOPE_TYPE
     *
     *  Mon Sep 29 17:58:40 CST 2014
     */
    public void setScopeType(String scopeType) {
        this.scopeType = scopeType == null ? null : scopeType.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_SCOPE_SETTING.IS_ENABLED
     *
     * @return the value of TOP_RECOMMEND_SCOPE_SETTING.IS_ENABLED
     *
     *  Mon Sep 29 17:58:40 CST 2014
     */
    public String getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_SCOPE_SETTING.IS_ENABLED
     *
     * @param isEnabled the value for TOP_RECOMMEND_SCOPE_SETTING.IS_ENABLED
     *
     *  Mon Sep 29 17:58:40 CST 2014
     */
    public void setIsEnabled(String isEnabled) {
        this.isEnabled = isEnabled == null ? null : isEnabled.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_SCOPE_SETTING.LAST_MODIFIED_BY
     *
     * @return the value of TOP_RECOMMEND_SCOPE_SETTING.LAST_MODIFIED_BY
     *
     *  Mon Sep 29 17:58:40 CST 2014
     */
    public Long getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_SCOPE_SETTING.LAST_MODIFIED_BY
     *
     * @param lastModifiedBy the value for TOP_RECOMMEND_SCOPE_SETTING.LAST_MODIFIED_BY
     *
     *  Mon Sep 29 17:58:40 CST 2014
     */
    public void setLastModifiedBy(Long lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy == null ? null : lastModifiedBy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_SCOPE_SETTING.LAST_MODIFIED_TIME
     *
     * @return the value of TOP_RECOMMEND_SCOPE_SETTING.LAST_MODIFIED_TIME
     *
     *  Mon Sep 29 17:58:40 CST 2014
     */
    public Date getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_SCOPE_SETTING.LAST_MODIFIED_TIME
     *
     * @param lastModifiedTime the value for TOP_RECOMMEND_SCOPE_SETTING.LAST_MODIFIED_TIME
     *
     *  Mon Sep 29 17:58:40 CST 2014
     */
    public void setLastModifiedTime(Date lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_RECOMMEND_SCOPE_SETTING
     *
     *  Mon Sep 29 17:58:40 CST 2014
     */
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof RecommendScopeSetting)) {
            return false;
        }
        RecommendScopeSetting other = (RecommendScopeSetting) that;
        return this.getShopId() == null ? other == null : this.getShopId().equals(other.getShopId())
            && this.getScopeType() == null ? other == null : this.getScopeType().equals(other.getScopeType())
            && this.getIsEnabled() == null ? other == null : this.getIsEnabled().equals(other.getIsEnabled())
            && this.getLastModifiedBy() == null ? other == null : this.getLastModifiedBy().equals(other.getLastModifiedBy())
            && this.getLastModifiedTime() == null ? other == null : this.getLastModifiedTime().equals(other.getLastModifiedTime());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_RECOMMEND_SCOPE_SETTING
     *
     *  Mon Sep 29 17:58:40 CST 2014
     */
    public int hashCode() {
        int hash = 23;
        if (getShopId() != null) {
            hash *= getShopId().hashCode();
        }
        if (getScopeType() != null) {
            hash *= getScopeType().hashCode();
        }
        if (getIsEnabled() != null) {
            hash *= getIsEnabled().hashCode();
        }
        if (getLastModifiedBy() != null) {
            hash *= getLastModifiedBy().hashCode();
        }
        if (getLastModifiedTime() != null) {
            hash *= getLastModifiedTime().hashCode();
        }
        return hash;
    }
}