package com.dream.recommend.model;

import java.io.Serializable;
import java.util.Date;

public class RecommendSpecified implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_SPECIFIED.ID
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_SPECIFIED.SHOP_ID
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    private Long shopId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_SPECIFIED.TYPE
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    private String type;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_SPECIFIED.ITEM_ID
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    private Long itemId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_SPECIFIED.ITEM_NAME
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    private String itemName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_SPECIFIED.LAST_MODIFIED_BY
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    private Long lastModifiedBy;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_RECOMMEND_SPECIFIED.LAST_MODIFIED_TIME
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    private Date lastModifiedTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table TOP_RECOMMEND_SPECIFIED
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_SPECIFIED.ID
     *
     * @return the value of TOP_RECOMMEND_SPECIFIED.ID
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_SPECIFIED.ID
     *
     * @param id the value for TOP_RECOMMEND_SPECIFIED.ID
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    public void setId(Long id) {
        this.id = id == null ? null : id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_SPECIFIED.SHOP_ID
     *
     * @return the value of TOP_RECOMMEND_SPECIFIED.SHOP_ID
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_SPECIFIED.SHOP_ID
     *
     * @param shopId the value for TOP_RECOMMEND_SPECIFIED.SHOP_ID
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_SPECIFIED.TYPE
     *
     * @return the value of TOP_RECOMMEND_SPECIFIED.TYPE
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_SPECIFIED.TYPE
     *
     * @param type the value for TOP_RECOMMEND_SPECIFIED.TYPE
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_SPECIFIED.ITEM_ID
     *
     * @return the value of TOP_RECOMMEND_SPECIFIED.ITEM_ID
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_SPECIFIED.ITEM_ID
     *
     * @param itemId the value for TOP_RECOMMEND_SPECIFIED.ITEM_ID
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_SPECIFIED.ITEM_NAME
     *
     * @return the value of TOP_RECOMMEND_SPECIFIED.ITEM_NAME
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_SPECIFIED.ITEM_NAME
     *
     * @param itemName the value for TOP_RECOMMEND_SPECIFIED.ITEM_NAME
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_SPECIFIED.LAST_MODIFIED_BY
     *
     * @return the value of TOP_RECOMMEND_SPECIFIED.LAST_MODIFIED_BY
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    public Long getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_SPECIFIED.LAST_MODIFIED_BY
     *
     * @param lastModifiedBy the value for TOP_RECOMMEND_SPECIFIED.LAST_MODIFIED_BY
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    public void setLastModifiedBy(Long lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_RECOMMEND_SPECIFIED.LAST_MODIFIED_TIME
     *
     * @return the value of TOP_RECOMMEND_SPECIFIED.LAST_MODIFIED_TIME
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    public Date getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_RECOMMEND_SPECIFIED.LAST_MODIFIED_TIME
     *
     * @param lastModifiedTime the value for TOP_RECOMMEND_SPECIFIED.LAST_MODIFIED_TIME
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    public void setLastModifiedTime(Date lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_RECOMMEND_SPECIFIED
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof RecommendSpecified)) {
            return false;
        }
        RecommendSpecified other = (RecommendSpecified) that;
        return this.getId() == null ? other == null : this.getId().equals(other.getId())
            && this.getShopId() == null ? other == null : this.getShopId().equals(other.getShopId())
            && this.getType() == null ? other == null : this.getType().equals(other.getType())
            && this.getItemId() == null ? other == null : this.getItemId().equals(other.getItemId())
            && this.getItemName() == null ? other == null : this.getItemName().equals(other.getItemName())
            && this.getLastModifiedBy() == null ? other == null : this.getLastModifiedBy().equals(other.getLastModifiedBy())
            && this.getLastModifiedTime() == null ? other == null : this.getLastModifiedTime().equals(other.getLastModifiedTime());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_RECOMMEND_SPECIFIED
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getId() != null) {
            hash *= getId().hashCode();
        }
        if (getShopId() != null) {
            hash *= getShopId().hashCode();
        }
        if (getType() != null) {
            hash *= getType().hashCode();
        }
        if (getItemId() != null) {
            hash *= getItemId().hashCode();
        }
        if (getItemName() != null) {
            hash *= getItemName().hashCode();
        }
        if (getLastModifiedBy() != null) {
            hash *= getLastModifiedBy().hashCode();
        }
        if (getLastModifiedTime() != null) {
            hash *= getLastModifiedTime().hashCode();
        }
        return hash;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_RECOMMEND_SPECIFIED
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    public RecommendSpecified() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_RECOMMEND_SPECIFIED
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    public RecommendSpecified(Long id) {
        this.id = id;
    }
}