/*
 * Powered By [com.dream.rapid]
 * GitHub: https://github.com/wallace46886799
 * Since 2008 - 2014
 */

package com.dream.shop.dao;

import org.springframework.stereotype.Repository;

import com.dream.rapid.base.BaseIbatisDao;
import com.dream.rapid.page.Page;
import com.dream.shop.model.Shop;
import com.dream.shop.model.ShopCriteria;
import com.dream.shop.vo.query.ShopQuery;
/**
 * @author Frank email:46886799#163.com
 * @version 1.0
 * @since 1.0
 */


@Repository
public class ShopDao extends BaseIbatisDao<Shop,java.lang.Long,ShopCriteria>{

	//================================********Generated code start here********================================
	
	@Override
	public String getIbatisSqlMapNamespace() {
		return "TOP_SHOP";
	}
	
	
	/**
	 * 分页查询
	 * @param query
	 * @return
	 */
	public Page findPage(ShopQuery query) {
		return pageQuery(getIbatisSqlMapNamespace() + ".findPage",query);
	}
	
	

	@Override
	protected void prepareObjectForSaveOrUpdate(Shop source,Shop record) {
		
	}	
	
    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table TOP_SHOP
     *
     *  Mon Sep 29 17:47:09 CST 2014
     */
    private static class UpdateByCriteriaParms extends ShopCriteria {
        private Object record;

        public UpdateByCriteriaParms(Object record, ShopCriteria criteria) {
            super(criteria);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }



	@Override
	protected ShopCriteria getCriteriaParam(Shop record, ShopCriteria criteria) {
		return new UpdateByCriteriaParms(record,criteria);
	}
	
	
	//================================********Generated code end here********================================
	
	//================================********Customized code start here********==============================
	
	
	
	//================================********Customized code end here********================================

	
	
}
