package com.dream.shop.model;

import java.io.Serializable;
import java.util.Date;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.annotate.JsonProperty;

public class ShopCategory implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_SHOP_CATEGORY.CID
     *{ id:23, pId:2, name:"禁止勾选 2-3", doCheck:false}
     *  Tue Oct 07 17:27:43 CST 2014
     */
	@JsonProperty("id")
    private Long cid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_SHOP_CATEGORY.PARENT_CID
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
	@JsonProperty("pId")
    private Long parentCid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_SHOP_CATEGORY.NAME
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_SHOP_CATEGORY.PIC_URL
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    @JsonIgnore
    private String picUrl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_SHOP_CATEGORY.SORT_ORDER
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    @JsonIgnore
    private Integer sortOrder;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_SHOP_CATEGORY.TYPE
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    @JsonIgnore
    private String type;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_SHOP_CATEGORY.SHOP_ID
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    @JsonIgnore
    private Long shopId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_SHOP_CATEGORY.CREATE_TIME
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    @JsonIgnore
    private Date createTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_SHOP_CATEGORY.REFRESH_TIME
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    @JsonIgnore
    private Date refreshTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table TOP_SHOP_CATEGORY
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_SHOP_CATEGORY.CID
     *
     * @return the value of TOP_SHOP_CATEGORY.CID
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_SHOP_CATEGORY.CID
     *
     * @param cid the value for TOP_SHOP_CATEGORY.CID
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_SHOP_CATEGORY.PARENT_CID
     *
     * @return the value of TOP_SHOP_CATEGORY.PARENT_CID
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    public Long getParentCid() {
        return parentCid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_SHOP_CATEGORY.PARENT_CID
     *
     * @param parentCid the value for TOP_SHOP_CATEGORY.PARENT_CID
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    public void setParentCid(Long parentCid) {
        this.parentCid = parentCid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_SHOP_CATEGORY.NAME
     *
     * @return the value of TOP_SHOP_CATEGORY.NAME
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_SHOP_CATEGORY.NAME
     *
     * @param name the value for TOP_SHOP_CATEGORY.NAME
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_SHOP_CATEGORY.PIC_URL
     *
     * @return the value of TOP_SHOP_CATEGORY.PIC_URL
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_SHOP_CATEGORY.PIC_URL
     *
     * @param picUrl the value for TOP_SHOP_CATEGORY.PIC_URL
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_SHOP_CATEGORY.SORT_ORDER
     *
     * @return the value of TOP_SHOP_CATEGORY.SORT_ORDER
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_SHOP_CATEGORY.SORT_ORDER
     *
     * @param sortOrder the value for TOP_SHOP_CATEGORY.SORT_ORDER
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_SHOP_CATEGORY.TYPE
     *
     * @return the value of TOP_SHOP_CATEGORY.TYPE
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_SHOP_CATEGORY.TYPE
     *
     * @param type the value for TOP_SHOP_CATEGORY.TYPE
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_SHOP_CATEGORY.SHOP_ID
     *
     * @return the value of TOP_SHOP_CATEGORY.SHOP_ID
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_SHOP_CATEGORY.SHOP_ID
     *
     * @param shopId the value for TOP_SHOP_CATEGORY.SHOP_ID
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_SHOP_CATEGORY.CREATE_TIME
     *
     * @return the value of TOP_SHOP_CATEGORY.CREATE_TIME
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_SHOP_CATEGORY.CREATE_TIME
     *
     * @param createTime the value for TOP_SHOP_CATEGORY.CREATE_TIME
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_SHOP_CATEGORY.REFRESH_TIME
     *
     * @return the value of TOP_SHOP_CATEGORY.REFRESH_TIME
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    public Date getRefreshTime() {
        return refreshTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_SHOP_CATEGORY.REFRESH_TIME
     *
     * @param refreshTime the value for TOP_SHOP_CATEGORY.REFRESH_TIME
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    public void setRefreshTime(Date refreshTime) {
        this.refreshTime = refreshTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_SHOP_CATEGORY
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof ShopCategory)) {
            return false;
        }
        ShopCategory other = (ShopCategory) that;
        return this.getCid() == null ? other == null : this.getCid().equals(other.getCid())
            && this.getParentCid() == null ? other == null : this.getParentCid().equals(other.getParentCid())
            && this.getName() == null ? other == null : this.getName().equals(other.getName())
            && this.getPicUrl() == null ? other == null : this.getPicUrl().equals(other.getPicUrl())
            && this.getSortOrder() == null ? other == null : this.getSortOrder().equals(other.getSortOrder())
            && this.getType() == null ? other == null : this.getType().equals(other.getType())
            && this.getShopId() == null ? other == null : this.getShopId().equals(other.getShopId())
            && this.getCreateTime() == null ? other == null : this.getCreateTime().equals(other.getCreateTime())
            && this.getRefreshTime() == null ? other == null : this.getRefreshTime().equals(other.getRefreshTime());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_SHOP_CATEGORY
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getCid() != null) {
            hash *= getCid().hashCode();
        }
        if (getParentCid() != null) {
            hash *= getParentCid().hashCode();
        }
        if (getName() != null) {
            hash *= getName().hashCode();
        }
        if (getPicUrl() != null) {
            hash *= getPicUrl().hashCode();
        }
        if (getSortOrder() != null) {
            hash *= getSortOrder().hashCode();
        }
        if (getType() != null) {
            hash *= getType().hashCode();
        }
        if (getShopId() != null) {
            hash *= getShopId().hashCode();
        }
        if (getCreateTime() != null) {
            hash *= getCreateTime().hashCode();
        }
        if (getRefreshTime() != null) {
            hash *= getRefreshTime().hashCode();
        }
        return hash;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_SHOP_CATEGORY
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    public ShopCategory() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_SHOP_CATEGORY
     *
     *  Tue Oct 07 17:27:43 CST 2014
     */
    public ShopCategory(Long cid) {
        this.cid = cid;
    }
}