package com.dream.common.model;

import java.io.Serializable;

public class AppCode extends AppCodeKey implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_APP_CODE.CODE_NAME_CN
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    private String codeNameCn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_APP_CODE.CODE_NAME_EN
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    private String codeNameEn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_APP_CODE.CODE_VALUE
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    private String codeValue;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_APP_CODE.CODE_DESC
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    private String codeDesc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table TOP_APP_CODE
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_APP_CODE.CODE_NAME_CN
     *
     * @return the value of TOP_APP_CODE.CODE_NAME_CN
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    public String getCodeNameCn() {
        return codeNameCn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_APP_CODE.CODE_NAME_CN
     *
     * @param codeNameCn the value for TOP_APP_CODE.CODE_NAME_CN
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    public void setCodeNameCn(String codeNameCn) {
        this.codeNameCn = codeNameCn == null ? null : codeNameCn.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_APP_CODE.CODE_NAME_EN
     *
     * @return the value of TOP_APP_CODE.CODE_NAME_EN
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    public String getCodeNameEn() {
        return codeNameEn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_APP_CODE.CODE_NAME_EN
     *
     * @param codeNameEn the value for TOP_APP_CODE.CODE_NAME_EN
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    public void setCodeNameEn(String codeNameEn) {
        this.codeNameEn = codeNameEn == null ? null : codeNameEn.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_APP_CODE.CODE_VALUE
     *
     * @return the value of TOP_APP_CODE.CODE_VALUE
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    public String getCodeValue() {
        return codeValue;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_APP_CODE.CODE_VALUE
     *
     * @param codeValue the value for TOP_APP_CODE.CODE_VALUE
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    public void setCodeValue(String codeValue) {
        this.codeValue = codeValue == null ? null : codeValue.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_APP_CODE.CODE_DESC
     *
     * @return the value of TOP_APP_CODE.CODE_DESC
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    public String getCodeDesc() {
        return codeDesc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_APP_CODE.CODE_DESC
     *
     * @param codeDesc the value for TOP_APP_CODE.CODE_DESC
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    public void setCodeDesc(String codeDesc) {
        this.codeDesc = codeDesc == null ? null : codeDesc.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_APP_CODE
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof AppCode)) {
            return false;
        }
        AppCode other = (AppCode) that;
        return this.getGroupId() == null ? other == null : this.getGroupId().equals(other.getGroupId())
            && this.getSequence() == null ? other == null : this.getSequence().equals(other.getSequence())
            && this.getCodeNameCn() == null ? other == null : this.getCodeNameCn().equals(other.getCodeNameCn())
            && this.getCodeNameEn() == null ? other == null : this.getCodeNameEn().equals(other.getCodeNameEn())
            && this.getCodeValue() == null ? other == null : this.getCodeValue().equals(other.getCodeValue())
            && this.getCodeDesc() == null ? other == null : this.getCodeDesc().equals(other.getCodeDesc());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_APP_CODE
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getGroupId() != null) {
            hash *= getGroupId().hashCode();
        }
        if (getSequence() != null) {
            hash *= getSequence().hashCode();
        }
        if (getCodeNameCn() != null) {
            hash *= getCodeNameCn().hashCode();
        }
        if (getCodeNameEn() != null) {
            hash *= getCodeNameEn().hashCode();
        }
        if (getCodeValue() != null) {
            hash *= getCodeValue().hashCode();
        }
        if (getCodeDesc() != null) {
            hash *= getCodeDesc().hashCode();
        }
        return hash;
    }
}