package com.dream.common.model;

import java.io.Serializable;

public class AppCodeKey implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_APP_CODE.GROUP_ID
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    private String groupId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_APP_CODE.SEQUENCE
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    private Integer sequence;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table TOP_APP_CODE
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_APP_CODE.GROUP_ID
     *
     * @return the value of TOP_APP_CODE.GROUP_ID
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_APP_CODE.GROUP_ID
     *
     * @param groupId the value for TOP_APP_CODE.GROUP_ID
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_APP_CODE.SEQUENCE
     *
     * @return the value of TOP_APP_CODE.SEQUENCE
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_APP_CODE.SEQUENCE
     *
     * @param sequence the value for TOP_APP_CODE.SEQUENCE
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_APP_CODE
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof AppCodeKey)) {
            return false;
        }
        AppCodeKey other = (AppCodeKey) that;
        return this.getGroupId() == null ? other == null : this.getGroupId().equals(other.getGroupId())
            && this.getSequence() == null ? other == null : this.getSequence().equals(other.getSequence());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_APP_CODE
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getGroupId() != null) {
            hash *= getGroupId().hashCode();
        }
        if (getSequence() != null) {
            hash *= getSequence().hashCode();
        }
        return hash;
    }
}