package com.dream.common.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AppCodeCriteria {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table TOP_APP_CODE
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table TOP_APP_CODE
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_APP_CODE
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    public AppCodeCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_APP_CODE
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    protected AppCodeCriteria(AppCodeCriteria example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_APP_CODE
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_APP_CODE
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_APP_CODE
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_APP_CODE
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_APP_CODE
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_APP_CODE
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_APP_CODE
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table TOP_APP_CODE
     *
     *  Tue Oct 14 22:07:26 CST 2014
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andGroupIdIsNull() {
            addCriterion("GROUP_ID is null");
            return this;
        }

        public Criteria andGroupIdIsNotNull() {
            addCriterion("GROUP_ID is not null");
            return this;
        }

        public Criteria andGroupIdEqualTo(String value) {
            addCriterion("GROUP_ID =", value, "groupId");
            return this;
        }

        public Criteria andGroupIdNotEqualTo(String value) {
            addCriterion("GROUP_ID <>", value, "groupId");
            return this;
        }

        public Criteria andGroupIdGreaterThan(String value) {
            addCriterion("GROUP_ID >", value, "groupId");
            return this;
        }

        public Criteria andGroupIdGreaterThanOrEqualTo(String value) {
            addCriterion("GROUP_ID >=", value, "groupId");
            return this;
        }

        public Criteria andGroupIdLessThan(String value) {
            addCriterion("GROUP_ID <", value, "groupId");
            return this;
        }

        public Criteria andGroupIdLessThanOrEqualTo(String value) {
            addCriterion("GROUP_ID <=", value, "groupId");
            return this;
        }

        public Criteria andGroupIdLike(String value) {
            addCriterion("GROUP_ID like", value, "groupId");
            return this;
        }

        public Criteria andGroupIdNotLike(String value) {
            addCriterion("GROUP_ID not like", value, "groupId");
            return this;
        }

        public Criteria andGroupIdIn(List<String> values) {
            addCriterion("GROUP_ID in", values, "groupId");
            return this;
        }

        public Criteria andGroupIdNotIn(List<String> values) {
            addCriterion("GROUP_ID not in", values, "groupId");
            return this;
        }

        public Criteria andGroupIdBetween(String value1, String value2) {
            addCriterion("GROUP_ID between", value1, value2, "groupId");
            return this;
        }

        public Criteria andGroupIdNotBetween(String value1, String value2) {
            addCriterion("GROUP_ID not between", value1, value2, "groupId");
            return this;
        }

        public Criteria andSequenceIsNull() {
            addCriterion("SEQUENCE is null");
            return this;
        }

        public Criteria andSequenceIsNotNull() {
            addCriterion("SEQUENCE is not null");
            return this;
        }

        public Criteria andSequenceEqualTo(Integer value) {
            addCriterion("SEQUENCE =", value, "sequence");
            return this;
        }

        public Criteria andSequenceNotEqualTo(Integer value) {
            addCriterion("SEQUENCE <>", value, "sequence");
            return this;
        }

        public Criteria andSequenceGreaterThan(Integer value) {
            addCriterion("SEQUENCE >", value, "sequence");
            return this;
        }

        public Criteria andSequenceGreaterThanOrEqualTo(Integer value) {
            addCriterion("SEQUENCE >=", value, "sequence");
            return this;
        }

        public Criteria andSequenceLessThan(Integer value) {
            addCriterion("SEQUENCE <", value, "sequence");
            return this;
        }

        public Criteria andSequenceLessThanOrEqualTo(Integer value) {
            addCriterion("SEQUENCE <=", value, "sequence");
            return this;
        }

        public Criteria andSequenceIn(List<Integer> values) {
            addCriterion("SEQUENCE in", values, "sequence");
            return this;
        }

        public Criteria andSequenceNotIn(List<Integer> values) {
            addCriterion("SEQUENCE not in", values, "sequence");
            return this;
        }

        public Criteria andSequenceBetween(Integer value1, Integer value2) {
            addCriterion("SEQUENCE between", value1, value2, "sequence");
            return this;
        }

        public Criteria andSequenceNotBetween(Integer value1, Integer value2) {
            addCriterion("SEQUENCE not between", value1, value2, "sequence");
            return this;
        }

        public Criteria andCodeNameCnIsNull() {
            addCriterion("CODE_NAME_CN is null");
            return this;
        }

        public Criteria andCodeNameCnIsNotNull() {
            addCriterion("CODE_NAME_CN is not null");
            return this;
        }

        public Criteria andCodeNameCnEqualTo(String value) {
            addCriterion("CODE_NAME_CN =", value, "codeNameCn");
            return this;
        }

        public Criteria andCodeNameCnNotEqualTo(String value) {
            addCriterion("CODE_NAME_CN <>", value, "codeNameCn");
            return this;
        }

        public Criteria andCodeNameCnGreaterThan(String value) {
            addCriterion("CODE_NAME_CN >", value, "codeNameCn");
            return this;
        }

        public Criteria andCodeNameCnGreaterThanOrEqualTo(String value) {
            addCriterion("CODE_NAME_CN >=", value, "codeNameCn");
            return this;
        }

        public Criteria andCodeNameCnLessThan(String value) {
            addCriterion("CODE_NAME_CN <", value, "codeNameCn");
            return this;
        }

        public Criteria andCodeNameCnLessThanOrEqualTo(String value) {
            addCriterion("CODE_NAME_CN <=", value, "codeNameCn");
            return this;
        }

        public Criteria andCodeNameCnLike(String value) {
            addCriterion("CODE_NAME_CN like", value, "codeNameCn");
            return this;
        }

        public Criteria andCodeNameCnNotLike(String value) {
            addCriterion("CODE_NAME_CN not like", value, "codeNameCn");
            return this;
        }

        public Criteria andCodeNameCnIn(List<String> values) {
            addCriterion("CODE_NAME_CN in", values, "codeNameCn");
            return this;
        }

        public Criteria andCodeNameCnNotIn(List<String> values) {
            addCriterion("CODE_NAME_CN not in", values, "codeNameCn");
            return this;
        }

        public Criteria andCodeNameCnBetween(String value1, String value2) {
            addCriterion("CODE_NAME_CN between", value1, value2, "codeNameCn");
            return this;
        }

        public Criteria andCodeNameCnNotBetween(String value1, String value2) {
            addCriterion("CODE_NAME_CN not between", value1, value2, "codeNameCn");
            return this;
        }

        public Criteria andCodeNameEnIsNull() {
            addCriterion("CODE_NAME_EN is null");
            return this;
        }

        public Criteria andCodeNameEnIsNotNull() {
            addCriterion("CODE_NAME_EN is not null");
            return this;
        }

        public Criteria andCodeNameEnEqualTo(String value) {
            addCriterion("CODE_NAME_EN =", value, "codeNameEn");
            return this;
        }

        public Criteria andCodeNameEnNotEqualTo(String value) {
            addCriterion("CODE_NAME_EN <>", value, "codeNameEn");
            return this;
        }

        public Criteria andCodeNameEnGreaterThan(String value) {
            addCriterion("CODE_NAME_EN >", value, "codeNameEn");
            return this;
        }

        public Criteria andCodeNameEnGreaterThanOrEqualTo(String value) {
            addCriterion("CODE_NAME_EN >=", value, "codeNameEn");
            return this;
        }

        public Criteria andCodeNameEnLessThan(String value) {
            addCriterion("CODE_NAME_EN <", value, "codeNameEn");
            return this;
        }

        public Criteria andCodeNameEnLessThanOrEqualTo(String value) {
            addCriterion("CODE_NAME_EN <=", value, "codeNameEn");
            return this;
        }

        public Criteria andCodeNameEnLike(String value) {
            addCriterion("CODE_NAME_EN like", value, "codeNameEn");
            return this;
        }

        public Criteria andCodeNameEnNotLike(String value) {
            addCriterion("CODE_NAME_EN not like", value, "codeNameEn");
            return this;
        }

        public Criteria andCodeNameEnIn(List<String> values) {
            addCriterion("CODE_NAME_EN in", values, "codeNameEn");
            return this;
        }

        public Criteria andCodeNameEnNotIn(List<String> values) {
            addCriterion("CODE_NAME_EN not in", values, "codeNameEn");
            return this;
        }

        public Criteria andCodeNameEnBetween(String value1, String value2) {
            addCriterion("CODE_NAME_EN between", value1, value2, "codeNameEn");
            return this;
        }

        public Criteria andCodeNameEnNotBetween(String value1, String value2) {
            addCriterion("CODE_NAME_EN not between", value1, value2, "codeNameEn");
            return this;
        }

        public Criteria andCodeValueIsNull() {
            addCriterion("CODE_VALUE is null");
            return this;
        }

        public Criteria andCodeValueIsNotNull() {
            addCriterion("CODE_VALUE is not null");
            return this;
        }

        public Criteria andCodeValueEqualTo(String value) {
            addCriterion("CODE_VALUE =", value, "codeValue");
            return this;
        }

        public Criteria andCodeValueNotEqualTo(String value) {
            addCriterion("CODE_VALUE <>", value, "codeValue");
            return this;
        }

        public Criteria andCodeValueGreaterThan(String value) {
            addCriterion("CODE_VALUE >", value, "codeValue");
            return this;
        }

        public Criteria andCodeValueGreaterThanOrEqualTo(String value) {
            addCriterion("CODE_VALUE >=", value, "codeValue");
            return this;
        }

        public Criteria andCodeValueLessThan(String value) {
            addCriterion("CODE_VALUE <", value, "codeValue");
            return this;
        }

        public Criteria andCodeValueLessThanOrEqualTo(String value) {
            addCriterion("CODE_VALUE <=", value, "codeValue");
            return this;
        }

        public Criteria andCodeValueLike(String value) {
            addCriterion("CODE_VALUE like", value, "codeValue");
            return this;
        }

        public Criteria andCodeValueNotLike(String value) {
            addCriterion("CODE_VALUE not like", value, "codeValue");
            return this;
        }

        public Criteria andCodeValueIn(List<String> values) {
            addCriterion("CODE_VALUE in", values, "codeValue");
            return this;
        }

        public Criteria andCodeValueNotIn(List<String> values) {
            addCriterion("CODE_VALUE not in", values, "codeValue");
            return this;
        }

        public Criteria andCodeValueBetween(String value1, String value2) {
            addCriterion("CODE_VALUE between", value1, value2, "codeValue");
            return this;
        }

        public Criteria andCodeValueNotBetween(String value1, String value2) {
            addCriterion("CODE_VALUE not between", value1, value2, "codeValue");
            return this;
        }

        public Criteria andCodeDescIsNull() {
            addCriterion("CODE_DESC is null");
            return this;
        }

        public Criteria andCodeDescIsNotNull() {
            addCriterion("CODE_DESC is not null");
            return this;
        }

        public Criteria andCodeDescEqualTo(String value) {
            addCriterion("CODE_DESC =", value, "codeDesc");
            return this;
        }

        public Criteria andCodeDescNotEqualTo(String value) {
            addCriterion("CODE_DESC <>", value, "codeDesc");
            return this;
        }

        public Criteria andCodeDescGreaterThan(String value) {
            addCriterion("CODE_DESC >", value, "codeDesc");
            return this;
        }

        public Criteria andCodeDescGreaterThanOrEqualTo(String value) {
            addCriterion("CODE_DESC >=", value, "codeDesc");
            return this;
        }

        public Criteria andCodeDescLessThan(String value) {
            addCriterion("CODE_DESC <", value, "codeDesc");
            return this;
        }

        public Criteria andCodeDescLessThanOrEqualTo(String value) {
            addCriterion("CODE_DESC <=", value, "codeDesc");
            return this;
        }

        public Criteria andCodeDescLike(String value) {
            addCriterion("CODE_DESC like", value, "codeDesc");
            return this;
        }

        public Criteria andCodeDescNotLike(String value) {
            addCriterion("CODE_DESC not like", value, "codeDesc");
            return this;
        }

        public Criteria andCodeDescIn(List<String> values) {
            addCriterion("CODE_DESC in", values, "codeDesc");
            return this;
        }

        public Criteria andCodeDescNotIn(List<String> values) {
            addCriterion("CODE_DESC not in", values, "codeDesc");
            return this;
        }

        public Criteria andCodeDescBetween(String value1, String value2) {
            addCriterion("CODE_DESC between", value1, value2, "codeDesc");
            return this;
        }

        public Criteria andCodeDescNotBetween(String value1, String value2) {
            addCriterion("CODE_DESC not between", value1, value2, "codeDesc");
            return this;
        }
    }
}