package com.dream.common.model;

import java.io.Serializable;

public class SysParam implements Serializable {
	
	public SysParam(){
		
	}
	
	public SysParam(String id){
		this.id = id;
	}
	
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_SYS_PARAM.ID
     *
     *  Mon Sep 29 17:41:14 CST 2014
     */
    private String id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_SYS_PARAM.KEY
     *
     *  Mon Sep 29 17:41:14 CST 2014
     */
    private String key;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_SYS_PARAM.VALUE
     *
     *  Mon Sep 29 17:41:14 CST 2014
     */
    private String value;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_SYS_PARAM.STATUS
     *
     *  Mon Sep 29 17:41:14 CST 2014
     */
    private String status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_SYS_PARAM.DESC
     *
     *  Mon Sep 29 17:41:14 CST 2014
     */
    private String desc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table TOP_SYS_PARAM
     *
     *  Mon Sep 29 17:41:14 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_SYS_PARAM.ID
     *
     * @return the value of TOP_SYS_PARAM.ID
     *
     *  Mon Sep 29 17:41:14 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_SYS_PARAM.ID
     *
     * @param id the value for TOP_SYS_PARAM.ID
     *
     *  Mon Sep 29 17:41:14 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_SYS_PARAM.KEY
     *
     * @return the value of TOP_SYS_PARAM.KEY
     *
     *  Mon Sep 29 17:41:14 CST 2014
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_SYS_PARAM.KEY
     *
     * @param key the value for TOP_SYS_PARAM.KEY
     *
     *  Mon Sep 29 17:41:14 CST 2014
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_SYS_PARAM.VALUE
     *
     * @return the value of TOP_SYS_PARAM.VALUE
     *
     *  Mon Sep 29 17:41:14 CST 2014
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_SYS_PARAM.VALUE
     *
     * @param value the value for TOP_SYS_PARAM.VALUE
     *
     *  Mon Sep 29 17:41:14 CST 2014
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_SYS_PARAM.STATUS
     *
     * @return the value of TOP_SYS_PARAM.STATUS
     *
     *  Mon Sep 29 17:41:14 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_SYS_PARAM.STATUS
     *
     * @param status the value for TOP_SYS_PARAM.STATUS
     *
     *  Mon Sep 29 17:41:14 CST 2014
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_SYS_PARAM.DESC
     *
     * @return the value of TOP_SYS_PARAM.DESC
     *
     *  Mon Sep 29 17:41:14 CST 2014
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_SYS_PARAM.DESC
     *
     * @param desc the value for TOP_SYS_PARAM.DESC
     *
     *  Mon Sep 29 17:41:14 CST 2014
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_SYS_PARAM
     *
     *  Mon Sep 29 17:41:14 CST 2014
     */
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof SysParam)) {
            return false;
        }
        SysParam other = (SysParam) that;
        return this.getId() == null ? other == null : this.getId().equals(other.getId())
            && this.getKey() == null ? other == null : this.getKey().equals(other.getKey())
            && this.getValue() == null ? other == null : this.getValue().equals(other.getValue())
            && this.getStatus() == null ? other == null : this.getStatus().equals(other.getStatus())
            && this.getDesc() == null ? other == null : this.getDesc().equals(other.getDesc());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_SYS_PARAM
     *
     *  Mon Sep 29 17:41:14 CST 2014
     */
    public int hashCode() {
        int hash = 23;
        if (getId() != null) {
            hash *= getId().hashCode();
        }
        if (getKey() != null) {
            hash *= getKey().hashCode();
        }
        if (getValue() != null) {
            hash *= getValue().hashCode();
        }
        if (getStatus() != null) {
            hash *= getStatus().hashCode();
        }
        if (getDesc() != null) {
            hash *= getDesc().hashCode();
        }
        return hash;
    }
}