/*
 * Powered By [com.dream.rapid]
 * GitHub: https://github.com/wallace46886799
 * Since 2008 - 2014
 */

package com.dream.recommend.dao;

import org.springframework.stereotype.Repository;

import com.dream.rapid.base.BaseIbatisDao;
import com.dream.rapid.page.Page;
import com.dream.recommend.model.RecommendLog;
import com.dream.recommend.model.RecommendLogCriteria;
import com.dream.recommend.vo.query.RecommendLogQuery;
/**
 * @author Frank email:46886799#163.com
 * @version 1.0
 * @since 1.0
 */


@Repository
public class RecommendLogDao extends BaseIbatisDao<RecommendLog,java.lang.String,RecommendLogCriteria>{

	//================================********Generated code start here********================================
	
	@Override
	public String getIbatisSqlMapNamespace() {
		return "TOP_RECOMMEND_LOG";
	}
	/**
	 * 分页查询
	 * @param query
	 * @return
	 */
	public Page findPage(RecommendLogQuery query) {
		return pageQuery("RecommendLog.findPage",query);
	}

	@Override
	protected void prepareObjectForSaveOrUpdate(RecommendLog source,RecommendLog dest) {
	}
	

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table TOP_RECOMMEND_LOG
     *
     *  Mon Sep 29 17:59:35 CST 2014
     */
    private static class UpdateByCriteriaParms extends RecommendLogCriteria {
        private Object record;

        public UpdateByCriteriaParms(Object record, RecommendLogCriteria criteria) {
            super(criteria);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }


	@Override
	protected RecommendLogCriteria getCriteriaParam(RecommendLog record,
			RecommendLogCriteria criteria) {
		return new UpdateByCriteriaParms(record,criteria);
	}
	

	//================================********Generated code end here********================================
	
	//================================********Customized code start here********==============================
	
	
	
	//================================********Customized code end here********================================

	
	
}
