package com.dream.recommend.dao;

import com.dream.rapid.base.BaseIbatisDao;
import com.dream.recommend.model.RecommendSpecified;
import com.dream.recommend.model.RecommendSpecifiedCriteria;
import org.springframework.stereotype.Repository;

@Repository
public class RecommendSpecifiedDao extends BaseIbatisDao<RecommendSpecified, String, RecommendSpecifiedCriteria> {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_RECOMMEND_SPECIFIED
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    public RecommendSpecifiedDao() {
        super();
    }

    protected void prepareObjectForSaveOrUpdate(RecommendSpecified record, RecommendSpecified first) {
        record.setId(first.getId());
    }

    protected String getIbatisSqlMapNamespace() {
        return "TOP_RECOMMEND_SPECIFIED";
    }

    protected RecommendSpecifiedCriteria getCriteriaParam(RecommendSpecified record, RecommendSpecifiedCriteria criteria) {
        return new UpdateByCriteriaParms(record,criteria);
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table TOP_RECOMMEND_SPECIFIED
     *
     *  Sun Oct 05 21:44:21 CST 2014
     */
    private static class UpdateByCriteriaParms extends RecommendSpecifiedCriteria {
        private Object record;

        public UpdateByCriteriaParms(Object record, RecommendSpecifiedCriteria criteria) {
            super(criteria);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}