package com.dream.recommend.dao;

import com.dream.rapid.base.BaseIbatisDao;
import com.dream.recommend.model.RecommendScopeCategory;
import com.dream.recommend.model.RecommendScopeCategoryCriteria;
import org.springframework.stereotype.Repository;

@Repository
public class RecommendScopeCategoryDao extends BaseIbatisDao<RecommendScopeCategory, String, RecommendScopeCategoryCriteria> {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_RECOMMEND_SCOPE_CATEGORY
     *
     *  Sun Oct 05 21:06:00 CST 2014
     */
    public RecommendScopeCategoryDao() {
        super();
    }

    protected void prepareObjectForSaveOrUpdate(RecommendScopeCategory record, RecommendScopeCategory first) {
        ;
    }

    protected String getIbatisSqlMapNamespace() {
        return "TOP_RECOMMEND_SCOPE_CATEGORY";
    }

    protected RecommendScopeCategoryCriteria getCriteriaParam(RecommendScopeCategory record, RecommendScopeCategoryCriteria criteria) {
        return new UpdateByCriteriaParms(record,criteria);
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table TOP_RECOMMEND_SCOPE_CATEGORY
     *
     *  Sun Oct 05 21:06:00 CST 2014
     */
    private static class UpdateByCriteriaParms extends RecommendScopeCategoryCriteria {
        private Object record;

        public UpdateByCriteriaParms(Object record, RecommendScopeCategoryCriteria criteria) {
            super(criteria);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}