/*
 * Powered By [com.dream.rapid]
 * GitHub: https://github.com/wallace46886799
 * Since 2008 - 2014
 */

package com.dream.recommend.dao;

import org.springframework.stereotype.Repository;

import com.dream.rapid.base.BaseIbatisDao;
import com.dream.rapid.page.Page;
import com.dream.recommend.model.RecommendModeSetting;
import com.dream.recommend.model.RecommendModeSettingCriteria;
import com.dream.recommend.vo.query.RecommendModeSettingQuery;
/**
 * @author Frank email:46886799#163.com
 * @version 1.0
 * @since 1.0
 */


@Repository
public class RecommendModeSettingDao extends BaseIbatisDao<RecommendModeSetting,java.lang.Long,RecommendModeSettingCriteria>{

	//================================********Generated code start here********================================
	
	@Override
	public String getIbatisSqlMapNamespace() {
		return "TOP_RECOMMEND_MODE_SETTING";
	}
	
	
	/**
	 * 分页查询
	 * @param query
	 * @return
	 */
	public Page findPage(RecommendModeSettingQuery query) {
		return pageQuery(getIbatisSqlMapNamespace()+".findPage",query);
	}
	
	
	/**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table TOP_RECOMMEND_MODE_SETTING
     *
     *  Mon Sep 29 17:59:18 CST 2014
     */
    private static class UpdateByCriteriaParms extends RecommendModeSettingCriteria {
        private Object record;

        public UpdateByCriteriaParms(Object record, RecommendModeSettingCriteria criteria) {
            super(criteria);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	protected void prepareObjectForSaveOrUpdate(RecommendModeSetting source,RecommendModeSetting record) {
		
	}


	@Override
	protected RecommendModeSettingCriteria getCriteriaParam(
			RecommendModeSetting record, RecommendModeSettingCriteria criteria) {
		return new UpdateByCriteriaParms(record,criteria);
	}

	//================================********Generated code end here********================================
	
	//================================********Customized code start here********==============================
	
	
	
	//================================********Customized code end here********================================

	
	
}
