package com.dream.recommend.dao;

import com.dream.rapid.base.BaseIbatisDao;
import com.dream.recommend.model.RecommendStatus;
import com.dream.recommend.model.RecommendStatusCriteria;
import org.springframework.stereotype.Repository;

@Repository
public class RecommendStatusDao extends BaseIbatisDao<RecommendStatus, Long, RecommendStatusCriteria> {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_RECOMMEND_STATUS
     *
     *  Sun Oct 05 20:41:58 CST 2014
     */
    public RecommendStatusDao() {
        super();
    }

    protected void prepareObjectForSaveOrUpdate(RecommendStatus record,RecommendStatus first) {
        ;
    }

    protected String getIbatisSqlMapNamespace() {
        return "TOP_RECOMMEND_STATUS";
    }

    protected RecommendStatusCriteria getCriteriaParam(RecommendStatus record, RecommendStatusCriteria criteria) {
        return new UpdateByCriteriaParms(record,criteria);
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table TOP_RECOMMEND_STATUS
     *
     *  Sun Oct 05 20:41:58 CST 2014
     */
    private static class UpdateByCriteriaParms extends RecommendStatusCriteria {
        private Object record;

        public UpdateByCriteriaParms(Object record, RecommendStatusCriteria criteria) {
            super(criteria);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}