package com.dream.item.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Item implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.ID
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.NUM_IID
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private Long numIid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.CID
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private Integer cid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.SELLER_CIDS
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private String sellerCids;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.PROPS
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private String props;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.PIC_URL
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private String picUrl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.NUM
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private String num;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.LIST_TIME
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private Date listTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.DELIST_TIME
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private Date delistTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.PRICE
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private BigDecimal price;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.HAS_DISCOUNT
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private String hasDiscount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.HAS_INVOICE
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private String hasInvoice;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.HAS_WARRANTY
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private String hasWarranty;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.HAS_SHOWCASE
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private String hasShowcase;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.MODIFIED
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private Date modified;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.APPROVE_STATUS
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private String approveStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.POSTAGE_ID
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private Integer postageId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.IS_VIRTUAL
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private String isVirtual;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.IS_TAOBAO
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private String isTaobao;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.IS_EX
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private String isEx;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.TITLE
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private String title;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.NICK
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private String nick;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.TYPE
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private String type;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.VALID_THRU
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private String validThru;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.OUTER_ID
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private String outerId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.ONSALE_STATUS
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private String onsaleStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column TOP_ITEM.SOLD_QUANTITY
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private Integer soldQuantity;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table TOP_ITEM
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.ID
     *
     * @return the value of TOP_ITEM.ID
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.ID
     *
     * @param id the value for TOP_ITEM.ID
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.NUM_IID
     *
     * @return the value of TOP_ITEM.NUM_IID
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public Long getNumIid() {
        return numIid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.NUM_IID
     *
     * @param numIid the value for TOP_ITEM.NUM_IID
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setNumIid(Long numIid) {
        this.numIid = numIid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.CID
     *
     * @return the value of TOP_ITEM.CID
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.CID
     *
     * @param cid the value for TOP_ITEM.CID
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.SELLER_CIDS
     *
     * @return the value of TOP_ITEM.SELLER_CIDS
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public String getSellerCids() {
        return sellerCids;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.SELLER_CIDS
     *
     * @param sellerCids the value for TOP_ITEM.SELLER_CIDS
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setSellerCids(String sellerCids) {
        this.sellerCids = sellerCids == null ? null : sellerCids.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.PROPS
     *
     * @return the value of TOP_ITEM.PROPS
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public String getProps() {
        return props;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.PROPS
     *
     * @param props the value for TOP_ITEM.PROPS
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setProps(String props) {
        this.props = props == null ? null : props.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.PIC_URL
     *
     * @return the value of TOP_ITEM.PIC_URL
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.PIC_URL
     *
     * @param picUrl the value for TOP_ITEM.PIC_URL
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.NUM
     *
     * @return the value of TOP_ITEM.NUM
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.NUM
     *
     * @param num the value for TOP_ITEM.NUM
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.LIST_TIME
     *
     * @return the value of TOP_ITEM.LIST_TIME
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public Date getListTime() {
        return listTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.LIST_TIME
     *
     * @param listTime the value for TOP_ITEM.LIST_TIME
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setListTime(Date listTime) {
        this.listTime = listTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.DELIST_TIME
     *
     * @return the value of TOP_ITEM.DELIST_TIME
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public Date getDelistTime() {
        return delistTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.DELIST_TIME
     *
     * @param delistTime the value for TOP_ITEM.DELIST_TIME
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setDelistTime(Date delistTime) {
        this.delistTime = delistTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.PRICE
     *
     * @return the value of TOP_ITEM.PRICE
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.PRICE
     *
     * @param price the value for TOP_ITEM.PRICE
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.HAS_DISCOUNT
     *
     * @return the value of TOP_ITEM.HAS_DISCOUNT
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public String getHasDiscount() {
        return hasDiscount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.HAS_DISCOUNT
     *
     * @param hasDiscount the value for TOP_ITEM.HAS_DISCOUNT
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setHasDiscount(String hasDiscount) {
        this.hasDiscount = hasDiscount == null ? null : hasDiscount.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.HAS_INVOICE
     *
     * @return the value of TOP_ITEM.HAS_INVOICE
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public String getHasInvoice() {
        return hasInvoice;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.HAS_INVOICE
     *
     * @param hasInvoice the value for TOP_ITEM.HAS_INVOICE
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setHasInvoice(String hasInvoice) {
        this.hasInvoice = hasInvoice == null ? null : hasInvoice.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.HAS_WARRANTY
     *
     * @return the value of TOP_ITEM.HAS_WARRANTY
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public String getHasWarranty() {
        return hasWarranty;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.HAS_WARRANTY
     *
     * @param hasWarranty the value for TOP_ITEM.HAS_WARRANTY
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setHasWarranty(String hasWarranty) {
        this.hasWarranty = hasWarranty == null ? null : hasWarranty.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.HAS_SHOWCASE
     *
     * @return the value of TOP_ITEM.HAS_SHOWCASE
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public String getHasShowcase() {
        return hasShowcase;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.HAS_SHOWCASE
     *
     * @param hasShowcase the value for TOP_ITEM.HAS_SHOWCASE
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setHasShowcase(String hasShowcase) {
        this.hasShowcase = hasShowcase == null ? null : hasShowcase.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.MODIFIED
     *
     * @return the value of TOP_ITEM.MODIFIED
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.MODIFIED
     *
     * @param modified the value for TOP_ITEM.MODIFIED
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.APPROVE_STATUS
     *
     * @return the value of TOP_ITEM.APPROVE_STATUS
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public String getApproveStatus() {
        return approveStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.APPROVE_STATUS
     *
     * @param approveStatus the value for TOP_ITEM.APPROVE_STATUS
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setApproveStatus(String approveStatus) {
        this.approveStatus = approveStatus == null ? null : approveStatus.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.POSTAGE_ID
     *
     * @return the value of TOP_ITEM.POSTAGE_ID
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public Integer getPostageId() {
        return postageId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.POSTAGE_ID
     *
     * @param postageId the value for TOP_ITEM.POSTAGE_ID
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setPostageId(Integer postageId) {
        this.postageId = postageId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.IS_VIRTUAL
     *
     * @return the value of TOP_ITEM.IS_VIRTUAL
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public String getIsVirtual() {
        return isVirtual;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.IS_VIRTUAL
     *
     * @param isVirtual the value for TOP_ITEM.IS_VIRTUAL
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setIsVirtual(String isVirtual) {
        this.isVirtual = isVirtual == null ? null : isVirtual.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.IS_TAOBAO
     *
     * @return the value of TOP_ITEM.IS_TAOBAO
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public String getIsTaobao() {
        return isTaobao;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.IS_TAOBAO
     *
     * @param isTaobao the value for TOP_ITEM.IS_TAOBAO
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setIsTaobao(String isTaobao) {
        this.isTaobao = isTaobao == null ? null : isTaobao.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.IS_EX
     *
     * @return the value of TOP_ITEM.IS_EX
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public String getIsEx() {
        return isEx;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.IS_EX
     *
     * @param isEx the value for TOP_ITEM.IS_EX
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setIsEx(String isEx) {
        this.isEx = isEx == null ? null : isEx.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.TITLE
     *
     * @return the value of TOP_ITEM.TITLE
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.TITLE
     *
     * @param title the value for TOP_ITEM.TITLE
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.NICK
     *
     * @return the value of TOP_ITEM.NICK
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.NICK
     *
     * @param nick the value for TOP_ITEM.NICK
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setNick(String nick) {
        this.nick = nick == null ? null : nick.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.TYPE
     *
     * @return the value of TOP_ITEM.TYPE
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.TYPE
     *
     * @param type the value for TOP_ITEM.TYPE
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.VALID_THRU
     *
     * @return the value of TOP_ITEM.VALID_THRU
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public String getValidThru() {
        return validThru;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.VALID_THRU
     *
     * @param validThru the value for TOP_ITEM.VALID_THRU
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setValidThru(String validThru) {
        this.validThru = validThru == null ? null : validThru.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.OUTER_ID
     *
     * @return the value of TOP_ITEM.OUTER_ID
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public String getOuterId() {
        return outerId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.OUTER_ID
     *
     * @param outerId the value for TOP_ITEM.OUTER_ID
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setOuterId(String outerId) {
        this.outerId = outerId == null ? null : outerId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.ONSALE_STATUS
     *
     * @return the value of TOP_ITEM.ONSALE_STATUS
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public String getOnsaleStatus() {
        return onsaleStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.ONSALE_STATUS
     *
     * @param onsaleStatus the value for TOP_ITEM.ONSALE_STATUS
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setOnsaleStatus(String onsaleStatus) {
        this.onsaleStatus = onsaleStatus == null ? null : onsaleStatus.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column TOP_ITEM.SOLD_QUANTITY
     *
     * @return the value of TOP_ITEM.SOLD_QUANTITY
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public Integer getSoldQuantity() {
        return soldQuantity;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column TOP_ITEM.SOLD_QUANTITY
     *
     * @param soldQuantity the value for TOP_ITEM.SOLD_QUANTITY
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public void setSoldQuantity(Integer soldQuantity) {
        this.soldQuantity = soldQuantity;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_ITEM
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof Item)) {
            return false;
        }
        Item other = (Item) that;
        return this.getId() == null ? other == null : this.getId().equals(other.getId())
            && this.getNumIid() == null ? other == null : this.getNumIid().equals(other.getNumIid());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table TOP_ITEM
     *
     *  Mon Sep 29 17:51:41 CST 2014
     */
    public int hashCode() {
        int hash = 23;
        if (getId() != null) {
            hash *= getId().hashCode();
        }
        if (getNumIid() != null) {
            hash *= getNumIid().hashCode();
        }
        if (getCid() != null) {
            hash *= getCid().hashCode();
        }
        if (getSellerCids() != null) {
            hash *= getSellerCids().hashCode();
        }
        if (getProps() != null) {
            hash *= getProps().hashCode();
        }
        if (getPicUrl() != null) {
            hash *= getPicUrl().hashCode();
        }
        if (getNum() != null) {
            hash *= getNum().hashCode();
        }
        if (getListTime() != null) {
            hash *= getListTime().hashCode();
        }
        if (getDelistTime() != null) {
            hash *= getDelistTime().hashCode();
        }
        if (getPrice() != null) {
            hash *= getPrice().hashCode();
        }
        if (getHasDiscount() != null) {
            hash *= getHasDiscount().hashCode();
        }
        if (getHasInvoice() != null) {
            hash *= getHasInvoice().hashCode();
        }
        if (getHasWarranty() != null) {
            hash *= getHasWarranty().hashCode();
        }
        if (getHasShowcase() != null) {
            hash *= getHasShowcase().hashCode();
        }
        if (getModified() != null) {
            hash *= getModified().hashCode();
        }
        if (getApproveStatus() != null) {
            hash *= getApproveStatus().hashCode();
        }
        if (getPostageId() != null) {
            hash *= getPostageId().hashCode();
        }
        if (getIsVirtual() != null) {
            hash *= getIsVirtual().hashCode();
        }
        if (getIsTaobao() != null) {
            hash *= getIsTaobao().hashCode();
        }
        if (getIsEx() != null) {
            hash *= getIsEx().hashCode();
        }
        if (getTitle() != null) {
            hash *= getTitle().hashCode();
        }
        if (getNick() != null) {
            hash *= getNick().hashCode();
        }
        if (getType() != null) {
            hash *= getType().hashCode();
        }
        if (getValidThru() != null) {
            hash *= getValidThru().hashCode();
        }
        if (getOuterId() != null) {
            hash *= getOuterId().hashCode();
        }
        if (getOnsaleStatus() != null) {
            hash *= getOnsaleStatus().hashCode();
        }
        if (getSoldQuantity() != null) {
            hash *= getSoldQuantity().hashCode();
        }
        return hash;
    }
}